// Originally generated by scripts/build-seed.mjs; titles + descriptions
// hand-rewritten in the 2026 voice pass (plain, warm, no hymnal-speak).
// Keys, metrics, and icons are stable — do not change `key` values
// (earned milestones persist by key).
// Content verified by the biblequest-seed-content workflow (safety + tone + theology lenses).
// Scripture text: World English Bible (public domain).

import type { MilestoneSeed } from "@/lib/questos/types";

export const seedMilestones: MilestoneSeed[] = [
  {
    "key": "first-step",
    "title": "First Step",
    "description": "Your first quest, done. That's how every pilgrimage starts.",
    "milestoneType": "first_step",
    "requirementMetric": "quest_completions",
    "requirementCount": 1,
    "iconKey": "path"
  },
  {
    "key": "first-prayer",
    "title": "First Prayer",
    "description": "You wrote your first prayer. Honest words count.",
    "milestoneType": "first_step",
    "requirementMetric": "prayers_created",
    "requirementCount": 1,
    "iconKey": "candle"
  },
  {
    "key": "first-reflection",
    "title": "First Reflection",
    "description": "You noticed something worth writing down. That's the whole practice.",
    "milestoneType": "first_step",
    "requirementMetric": "reflections_created",
    "requirementCount": 1,
    "iconKey": "leaf"
  },
  {
    "key": "first-answered-prayer",
    "title": "First Answer",
    "description": "You marked a prayer answered — worth remembering.",
    "milestoneType": "first_step",
    "requirementMetric": "prayers_answered",
    "requirementCount": 1,
    "iconKey": "bird"
  },
  {
    "key": "first-chapter",
    "title": "First Chapter",
    "description": "You read your first chapter. No schedule, no rush.",
    "milestoneType": "first_step",
    "requirementMetric": "chapters_read",
    "requirementCount": 1,
    "iconKey": "book"
  },
  {
    "key": "first-bookmark",
    "title": "First Verse",
    "description": "You saved your first verse — words worth coming back to.",
    "milestoneType": "first_step",
    "requirementMetric": "verses_bookmarked",
    "requirementCount": 1,
    "iconKey": "bookmark"
  },
  {
    "key": "seven-mornings",
    "title": "Seven Days",
    "description": "You showed up seven days. A rhythm is forming.",
    "milestoneType": "rhythm",
    "requirementMetric": "journey_days",
    "requirementCount": 7,
    "iconKey": "sun"
  },
  {
    "key": "month-of-mornings",
    "title": "Thirty Days",
    "description": "Thirty days, all told. That's a practice now.",
    "milestoneType": "rhythm",
    "requirementMetric": "journey_days",
    "requirementCount": 30,
    "iconKey": "sun"
  },
  {
    "key": "steady-steps",
    "title": "Ten Quests",
    "description": "Ten quests done, one at a time.",
    "milestoneType": "rhythm",
    "requirementMetric": "quest_completions",
    "requirementCount": 10,
    "iconKey": "path"
  },
  {
    "key": "into-the-story",
    "title": "Into the Story",
    "description": "Ten chapters read. The story is opening up.",
    "milestoneType": "scripture",
    "requirementMetric": "chapters_read",
    "requirementCount": 10,
    "iconKey": "book"
  },
  {
    "key": "deep-roots",
    "title": "Deep Roots",
    "description": "Twenty reflections. That kind of attention goes deep.",
    "milestoneType": "depth",
    "requirementMetric": "reflections_created",
    "requirementCount": 20,
    "iconKey": "tree"
  },
  {
    "key": "practice-of-prayer",
    "title": "Ten Prayers",
    "description": "Ten prayers written — an honest conversation with God, in practice.",
    "milestoneType": "prayer",
    "requirementMetric": "prayers_created",
    "requirementCount": 10,
    "iconKey": "candle"
  },
  {
    "key": "words-for-the-road",
    "title": "Ten Verses",
    "description": "Ten verses saved, each one worth returning to.",
    "milestoneType": "scripture",
    "requirementMetric": "verses_bookmarked",
    "requirementCount": 10,
    "iconKey": "bookmark"
  },
  {
    "key": "gathered-graces",
    "title": "Five Answers",
    "description": "Five prayers answered — and you noticed every one.",
    "milestoneType": "prayer",
    "requirementMetric": "prayers_answered",
    "requirementCount": 5,
    "iconKey": "star"
  },
  {
    "key": "kept-vigil",
    "title": "Steady in Prayer",
    "description": "Five quests centered on prayer. You keep showing up.",
    "milestoneType": "prayer",
    "requirementMetric": "quests_prayer",
    "requirementCount": 5,
    "iconKey": "lantern"
  },
  {
    "key": "by-lamplight",
    "title": "Word by Word",
    "description": "Seven Scripture quests. The Word is becoming familiar ground.",
    "milestoneType": "scripture",
    "requirementMetric": "quests_scripture",
    "requirementCount": 7,
    "iconKey": "lantern"
  },
  {
    "key": "encourager",
    "title": "Encourager",
    "description": "Five kindness quests — people leave a little lighter than you found them.",
    "milestoneType": "kindness",
    "requirementMetric": "quests_kindness",
    "requirementCount": 5,
    "iconKey": "flower"
  },
  {
    "key": "quiet-strength",
    "title": "Quiet Strength",
    "description": "You served others three times. No audience needed.",
    "milestoneType": "kindness",
    "requirementMetric": "quests_service",
    "requirementCount": 3,
    "iconKey": "tree"
  },
  {
    "key": "counted-gifts",
    "title": "Counted Gifts",
    "description": "Seven times you stopped to give thanks — for things easy to miss.",
    "milestoneType": "rhythm",
    "requirementMetric": "quests_gratitude",
    "requirementCount": 7,
    "iconKey": "star"
  },
  {
    "key": "still-waters",
    "title": "Still Waters",
    "description": "Three times you sat still and let that be enough.",
    "milestoneType": "depth",
    "requirementMetric": "quests_silence",
    "requirementCount": 3,
    "iconKey": "leaf"
  },
  {
    "key": "around-the-table",
    "title": "Around the Table",
    "description": "Faith practiced at home, three times over.",
    "milestoneType": "kindness",
    "requirementMetric": "quests_family",
    "requirementCount": 3,
    "iconKey": "flower"
  },
  {
    "key": "fellow-travelers",
    "title": "Fellow Travelers",
    "description": "Three quests with your community. The road is better with company.",
    "milestoneType": "kindness",
    "requirementMetric": "quests_community",
    "requirementCount": 3,
    "iconKey": "chapel"
  },
  {
    "key": "three-mornings",
    "title": "A Rhythm Begins",
    "description": "You returned on three different days. A practice starts by coming back.",
    "milestoneType": "rhythm",
    "requirementMetric": "journey_days",
    "requirementCount": 3,
    "iconKey": "sun"
  },
  {
    "key": "two-weeks-returning",
    "title": "Two Weeks Returning",
    "description": "Fourteen days along the road, made from ordinary moments of attention.",
    "milestoneType": "rhythm",
    "requirementMetric": "journey_days",
    "requirementCount": 14,
    "iconKey": "path"
  },
  {
    "key": "season-of-returning",
    "title": "A Season of Returning",
    "description": "You have returned on ninety days. The rhythm has had time to take root.",
    "milestoneType": "rhythm",
    "requirementMetric": "journey_days",
    "requirementCount": 90,
    "iconKey": "tree"
  },
  {
    "key": "many-small-steps",
    "title": "Many Small Steps",
    "description": "Twenty-five quests completed. Small acts have become a well-worn path.",
    "milestoneType": "rhythm",
    "requirementMetric": "quest_completions",
    "requirementCount": 25,
    "iconKey": "path"
  },
  {
    "key": "fifty-quests",
    "title": "The Longer Road",
    "description": "Fifty quests completed, each one lived beyond the screen.",
    "milestoneType": "rhythm",
    "requirementMetric": "quest_completions",
    "requirementCount": 50,
    "iconKey": "mountain"
  },
  {
    "key": "deeper-into-the-story",
    "title": "Deeper into the Story",
    "description": "Twenty-five chapters read. Familiar words are becoming a larger story.",
    "milestoneType": "scripture",
    "requirementMetric": "chapters_read",
    "requirementCount": 25,
    "iconKey": "open-book"
  },
  {
    "key": "prayer-woven-in",
    "title": "Prayer Woven In",
    "description": "Twenty-five prayers written across whatever the days held.",
    "milestoneType": "prayer",
    "requirementMetric": "prayers_created",
    "requirementCount": 25,
    "iconKey": "candle"
  },
  {
    "key": "pages-of-attention",
    "title": "Pages of Attention",
    "description": "Fifty reflections. You kept making room to notice what was happening within and around you.",
    "milestoneType": "depth",
    "requirementMetric": "reflections_created",
    "requirementCount": 50,
    "iconKey": "fountain"
  },
  {
    "key": "small-treasury",
    "title": "A Small Treasury",
    "description": "Twenty-five verses saved — a collection of words worth carrying.",
    "milestoneType": "scripture",
    "requirementMetric": "verses_bookmarked",
    "requirementCount": 25,
    "iconKey": "bookmark"
  },
  {
    "key": "graces-remembered",
    "title": "Graces Remembered",
    "description": "Ten prayers marked answered. You paused long enough to remember each one.",
    "milestoneType": "prayer",
    "requirementMetric": "prayers_answered",
    "requirementCount": 10,
    "iconKey": "bird"
  },
  {
    "key": "mercy-practiced",
    "title": "Mercy Practiced",
    "description": "Three forgiveness quests. Mercy took shape in choices you could actually make.",
    "milestoneType": "depth",
    "requirementMetric": "quests_forgiveness",
    "requirementCount": 3,
    "iconKey": "links"
  },
  {
    "key": "open-hands",
    "title": "Open Hands",
    "description": "Three generosity quests. You made room to give without needing to be noticed.",
    "milestoneType": "kindness",
    "requirementMetric": "quests_generosity",
    "requirementCount": 3,
    "iconKey": "wheat"
  },
  {
    "key": "steady-practice",
    "title": "Steady Practice",
    "description": "Five discipline quests. A faithful practice is being built one choice at a time.",
    "milestoneType": "rhythm",
    "requirementMetric": "quests_discipline",
    "requirementCount": 5,
    "iconKey": "lantern"
  },
  {
    "key": "ordinary-worship",
    "title": "Worship in Ordinary Days",
    "description": "Five worship quests. Attention and praise found a home in everyday life.",
    "milestoneType": "prayer",
    "requirementMetric": "quests_worship",
    "requirementCount": 5,
    "iconKey": "chapel"
  },
  {
    "key": "attentive-heart",
    "title": "An Attentive Heart",
    "description": "Five reflection quests. You practiced staying with what was worth noticing.",
    "milestoneType": "depth",
    "requirementMetric": "quests_reflection",
    "requirementCount": 5,
    "iconKey": "fountain"
  },
  {
    "key": "patient-steps",
    "title": "Patient Steps",
    "description": "Five patience quests. You kept choosing the slower, steadier way.",
    "milestoneType": "depth",
    "requirementMetric": "quests_patience",
    "requirementCount": 5,
    "iconKey": "path"
  }
];
