// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
// Milestones
// Content verified by the biblequest-seed-content workflow (safety + tone + theology lenses).
// Scripture text: World English Bible (public domain).

import type { MilestoneSeed } from "@/lib/questos/types";

export const seedMilestones: MilestoneSeed[] = [
  {
    "key": "first-step",
    "title": "First Step",
    "description": "You completed your first quest — a small step, and a true beginning.",
    "milestoneType": "first_step",
    "requirementMetric": "quest_completions",
    "requirementCount": 1,
    "iconKey": "path"
  },
  {
    "key": "first-prayer",
    "title": "A Prayer Begun",
    "description": "You wrote your first prayer, honest words offered in quiet.",
    "milestoneType": "first_step",
    "requirementMetric": "prayers_created",
    "requirementCount": 1,
    "iconKey": "candle"
  },
  {
    "key": "first-reflection",
    "title": "A Moment Noticed",
    "description": "You paused long enough to notice something, and wrote your first reflection.",
    "milestoneType": "first_step",
    "requirementMetric": "reflections_created",
    "requirementCount": 1,
    "iconKey": "leaf"
  },
  {
    "key": "first-answered-prayer",
    "title": "An Answer Came",
    "description": "You marked a prayer answered, and took a moment to receive it with gratitude.",
    "milestoneType": "first_step",
    "requirementMetric": "prayers_answered",
    "requirementCount": 1,
    "iconKey": "bird"
  },
  {
    "key": "first-chapter",
    "title": "The First Page",
    "description": "You opened the Scriptures and read your first chapter, at your own pace.",
    "milestoneType": "first_step",
    "requirementMetric": "chapters_read",
    "requirementCount": 1,
    "iconKey": "book"
  },
  {
    "key": "first-bookmark",
    "title": "A Verse to Carry",
    "description": "You kept your first verse, words to carry with you into the day.",
    "milestoneType": "first_step",
    "requirementMetric": "verses_bookmarked",
    "requirementCount": 1,
    "iconKey": "bookmark"
  },
  {
    "key": "seven-mornings",
    "title": "Seven Mornings",
    "description": "You returned on seven mornings, and a quiet rhythm began.",
    "milestoneType": "rhythm",
    "requirementMetric": "journey_days",
    "requirementCount": 7,
    "iconKey": "sun"
  },
  {
    "key": "month-of-mornings",
    "title": "A Month of Mornings",
    "description": "You returned for thirty days in all, one gentle morning at a time.",
    "milestoneType": "rhythm",
    "requirementMetric": "journey_days",
    "requirementCount": 30,
    "iconKey": "sun"
  },
  {
    "key": "steady-steps",
    "title": "Steady Steps",
    "description": "You completed ten quests, one steady step after another.",
    "milestoneType": "rhythm",
    "requirementMetric": "quest_completions",
    "requirementCount": 10,
    "iconKey": "path"
  },
  {
    "key": "into-the-story",
    "title": "Into the Story",
    "description": "You read ten chapters, letting Scripture unfold at its own pace.",
    "milestoneType": "scripture",
    "requirementMetric": "chapters_read",
    "requirementCount": 10,
    "iconKey": "book"
  },
  {
    "key": "deep-roots",
    "title": "Deep Roots",
    "description": "You wrote twenty reflections, and something in you grew quietly deeper.",
    "milestoneType": "depth",
    "requirementMetric": "reflections_created",
    "requirementCount": 20,
    "iconKey": "tree"
  },
  {
    "key": "practice-of-prayer",
    "title": "A Practice of Prayer",
    "description": "You brought ten prayers into words, learning the shape of honest conversation with God.",
    "milestoneType": "prayer",
    "requirementMetric": "prayers_created",
    "requirementCount": 10,
    "iconKey": "candle"
  },
  {
    "key": "words-for-the-road",
    "title": "Words for the Road",
    "description": "You gathered ten verses along the way, each one worth returning to.",
    "milestoneType": "scripture",
    "requirementMetric": "verses_bookmarked",
    "requirementCount": 10,
    "iconKey": "bookmark"
  },
  {
    "key": "gathered-graces",
    "title": "Gathered Graces",
    "description": "You noticed five answered prayers, and paused to give thanks for each one.",
    "milestoneType": "prayer",
    "requirementMetric": "prayers_answered",
    "requirementCount": 5,
    "iconKey": "star"
  },
  {
    "key": "kept-vigil",
    "title": "Kept Vigil",
    "description": "You returned to prayer through five quests, keeping quiet watch.",
    "milestoneType": "prayer",
    "requirementMetric": "quests_prayer",
    "requirementCount": 5,
    "iconKey": "lantern"
  },
  {
    "key": "by-lamplight",
    "title": "By Lamplight",
    "description": "You walked with Scripture through seven quests, a lamp for each step of the path.",
    "milestoneType": "scripture",
    "requirementMetric": "quests_scripture",
    "requirementCount": 7,
    "iconKey": "lantern"
  },
  {
    "key": "encourager",
    "title": "Encourager",
    "description": "You practiced kindness through five quests, leaving people a little lighter than you found them.",
    "milestoneType": "kindness",
    "requirementMetric": "quests_kindness",
    "requirementCount": 5,
    "iconKey": "flower"
  },
  {
    "key": "quiet-strength",
    "title": "Quiet Strength",
    "description": "You served others three times, quietly, without needing anyone to see.",
    "milestoneType": "kindness",
    "requirementMetric": "quests_service",
    "requirementCount": 3,
    "iconKey": "tree"
  },
  {
    "key": "counted-gifts",
    "title": "Counted Gifts",
    "description": "You paused to give thanks seven times, counting gifts easily missed.",
    "milestoneType": "rhythm",
    "requirementMetric": "quests_gratitude",
    "requirementCount": 7,
    "iconKey": "star"
  },
  {
    "key": "still-waters",
    "title": "Still Waters",
    "description": "You sat in stillness three times, and let the quiet do its slow work.",
    "milestoneType": "depth",
    "requirementMetric": "quests_silence",
    "requirementCount": 3,
    "iconKey": "leaf"
  },
  {
    "key": "around-the-table",
    "title": "Around the Table",
    "description": "You shared the journey with your family three times, faith practiced close to home.",
    "milestoneType": "kindness",
    "requirementMetric": "quests_family",
    "requirementCount": 3,
    "iconKey": "flower"
  },
  {
    "key": "fellow-travelers",
    "title": "Fellow Travelers",
    "description": "You walked with your community three times, and found the road kinder for the company.",
    "milestoneType": "kindness",
    "requirementMetric": "quests_community",
    "requirementCount": 3,
    "iconKey": "chapel"
  }
];
