// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
// Prayer prompts
// Content verified by the biblequest-seed-content workflow (safety + tone + theology lenses).
// Scripture text: World English Bible (public domain).

import type { PrayerPromptSeed } from "@/lib/questos/types";

export const prayerPrompts: PrayerPromptSeed[] = [
  {
    "id": "p01",
    "text": "Father, thank you for this morning. Walk with me through whatever it holds.",
    "category": "morning"
  },
  {
    "id": "p02",
    "text": "Lord, before the day gets loud, let me begin it with you.",
    "category": "morning"
  },
  {
    "id": "p03",
    "text": "God, I don't know what today will bring. Help me take it one step at a time, with you.",
    "category": "morning"
  },
  {
    "id": "p04",
    "text": "Father, the day is done. Help me set it down and rest in you.",
    "category": "evening"
  },
  {
    "id": "p05",
    "text": "Lord, thank you for carrying me through today, even the parts I barely noticed.",
    "category": "evening"
  },
  {
    "id": "p06",
    "text": "Jesus, quiet my mind tonight. Let me end this day grateful instead of restless.",
    "category": "evening"
  },
  {
    "id": "p07",
    "text": "God, open my eyes to the ordinary gifts I walk past every day.",
    "category": "gratitude"
  },
  {
    "id": "p08",
    "text": "Father, thank you for the small mercies of today, the ones I noticed and the ones I missed.",
    "category": "gratitude"
  },
  {
    "id": "p09",
    "text": "Lord, teach me a gratitude that lasts longer than the moment.",
    "category": "gratitude"
  },
  {
    "id": "p10",
    "text": "God, this is hard and I don't understand it. Stay close to me anyway.",
    "category": "difficulty"
  },
  {
    "id": "p11",
    "text": "Lord, I'm tired. Give me enough strength for today, and help me trust you with tomorrow.",
    "category": "difficulty"
  },
  {
    "id": "p12",
    "text": "Father, I can't see the way through this. Help me take the next step.",
    "category": "difficulty"
  },
  {
    "id": "p13",
    "text": "Lord, be near the person I'm worried about tonight. Hold them when I can't.",
    "category": "intercession"
  },
  {
    "id": "p14",
    "text": "Father, I bring you my friend who is hurting. Give them what I don't know how to give.",
    "category": "intercession"
  },
  {
    "id": "p15",
    "text": "God, comfort the people who feel forgotten today, and help me notice the ones close to me.",
    "category": "intercession"
  },
  {
    "id": "p16",
    "text": "Lord, slow me down. Teach me to sit quietly with you.",
    "category": "stillness"
  },
  {
    "id": "p17",
    "text": "Father, quiet the noise in me. I want to listen more than I speak.",
    "category": "stillness"
  },
  {
    "id": "p18",
    "text": "Jesus, I am always hurrying somewhere. Help me stop long enough to notice you here.",
    "category": "stillness"
  },
  {
    "id": "p19",
    "text": "Father, I'm holding on to an old hurt. Help me loosen my grip and let mercy in.",
    "category": "forgiveness"
  },
  {
    "id": "p20",
    "text": "God, forgive me for the ways I hurt people today, even the ways I didn't see.",
    "category": "forgiveness"
  },
  {
    "id": "p21",
    "text": "Jesus, forgiving this person feels beyond me. Begin it in me anyway.",
    "category": "forgiveness"
  },
  {
    "id": "p22",
    "text": "Lord, give me courage for the conversation I've been avoiding, and the wisdom to know whether and when the time is right.",
    "category": "courage"
  },
  {
    "id": "p23",
    "text": "God, help me do the right thing today, even when it's the quiet, unnoticed thing.",
    "category": "courage"
  },
  {
    "id": "p24",
    "text": "Father, I'm afraid. Remind me that you go with me.",
    "category": "courage"
  },
  {
    "id": "p25",
    "text": "Lord, give me patience with the people closest to me, the ones who see me at my worst.",
    "category": "family"
  },
  {
    "id": "p26",
    "text": "Father, bless my family today, especially the one I've been finding hard to love.",
    "category": "family"
  },
  {
    "id": "p27",
    "text": "Jesus, help me really listen at home tonight, instead of just waiting to speak.",
    "category": "family"
  },
  {
    "id": "p28",
    "text": "Lord, help me do today's work honestly and well, and then let it go.",
    "category": "work"
  },
  {
    "id": "p29",
    "text": "God, give me kindness for the people I work with, especially when the day runs long.",
    "category": "work"
  },
  {
    "id": "p30",
    "text": "Father, when my work feels small or unseen, remind me that it still matters to you.",
    "category": "work"
  },
  {
    "id": "p31",
    "text": "Jesus, make me quicker to be kind today than to be right.",
    "category": "general"
  },
  {
    "id": "p32",
    "text": "God, I don't have the words right now. Meet me here anyway.",
    "category": "general"
  }
];
