// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
// Quest templates
// Content verified by the biblequest-seed-content workflow (safety + tone + theology lenses).
// Scripture text: World English Bible (public domain).

import type { QuestTemplate } from "@/lib/questos/types";

export const seedQuests: QuestTemplate[] = [
  {
    "slug": "pray-before-you-rise",
    "title": "Pray Before You Rise",
    "category": "prayer",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Before you get up from your bed or couch, stay where you are a moment and offer God one honest sentence.",
    "whyItMatters": "The first words of a day quietly shape it. Speaking to God before anything else is an old and simple way to begin.",
    "scriptureReference": "Psalm 143:8",
    "scriptureText": "Cause me to hear your loving kindness in the morning, for I trust in you. Cause me to know the way in which I should walk, for I lift up my soul to you.",
    "reflectionPrompt": "What was it like to speak to God before reaching for anything else?",
    "prayerPrompt": "God, be the first voice I turn to today.",
    "growthType": "roots",
    "tags": [
      "morning",
      "rest",
      "beginning"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "pray-for-three-people-by-name",
    "title": "Pray for Three People by Name",
    "category": "prayer",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Bring three people to mind, one at a time, and ask God to be near each of them today.",
    "whyItMatters": "Praying for others by name is one of the oldest works of love. It is a quiet way of carrying the people we care about.",
    "scriptureReference": "Philippians 1:3-4",
    "scriptureText": "I thank my God whenever I remember you, always in every request of mine on behalf of you all, making my requests with joy,",
    "reflectionPrompt": "Who came to mind that you did not expect?",
    "prayerPrompt": "Lord, hold the people I carried to you today.",
    "growthType": "roots",
    "tags": [
      "intercession",
      "friendship",
      "love"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "the-lords-prayer-slowly",
    "title": "The Lord's Prayer, Slowly",
    "category": "prayer",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Pray the Lord's Prayer today one line at a time, pausing after each line to let it settle.",
    "whyItMatters": "This is the prayer Jesus gave his friends to teach them how to pray. Praying it slowly lets old words become your own.",
    "scriptureReference": "Matthew 6:9-13",
    "reflectionPrompt": "Which line stayed with you the longest?",
    "prayerPrompt": "Father, teach me to pray.",
    "growthType": "roots",
    "tags": [
      "tradition",
      "slowness",
      "jesus"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "pray-while-you-walk",
    "title": "Pray While You Walk",
    "category": "prayer",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Take a short walk today and turn what you notice along the way — a tree, a stranger, a worry — into simple prayer.",
    "whyItMatters": "Prayer does not need a quiet room. Walking with God is one of the oldest shapes of pilgrimage, and it fits inside an ordinary day.",
    "scriptureReference": "Psalm 19:1",
    "scriptureText": "The heavens declare the glory of God. The expanse shows his handiwork.",
    "reflectionPrompt": "What did you see differently because you were praying?",
    "prayerPrompt": "Lord, open my eyes as I go.",
    "growthType": "roots",
    "tags": [
      "walking",
      "creation",
      "noticing"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "pray-for-someone-hard-to-love",
    "title": "Pray for Someone Hard to Love",
    "category": "prayer",
    "durationMinutes": 10,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "In the quiet of your own heart, ask God to bless one person you find hard to love.",
    "whyItMatters": "Jesus asked his followers to pray for those who hurt them. This prayer is between you and God alone — it asks nothing else of you, and it can begin as small as a single sentence.",
    "scriptureReference": "Matthew 5:44",
    "scriptureText": "But I tell you, love your enemies, bless those who curse you, do good to those who hate you, and pray for those who mistreat you and persecute you,",
    "reflectionPrompt": "Did anything in you shift, even a little, as you prayed? It is all right if it did not.",
    "prayerPrompt": "Lord, soften what has gone hard in me.",
    "growthType": "roots",
    "tags": [
      "forgiveness",
      "mercy",
      "healing"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive",
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "carry-a-breath-prayer",
    "title": "Carry a Breath Prayer",
    "category": "prayer",
    "durationMinutes": 240,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Choose one short prayer — like \"Lord, have mercy\" or \"You are with me\" — and return to it gently through your afternoon.",
    "whyItMatters": "Christians have prayed short phrases like this for centuries. A breath prayer keeps a small door open to God in the middle of ordinary hours.",
    "scriptureReference": "1 Thessalonians 5:17",
    "scriptureText": "Pray without ceasing.",
    "reflectionPrompt": "When did the prayer return to you on its own?",
    "prayerPrompt": "Lord, stay near me through these ordinary hours.",
    "growthType": "roots",
    "tags": [
      "breath prayer",
      "presence",
      "work"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "five-minutes-of-silence",
    "title": "Five Minutes of Silence",
    "category": "silence",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Set your phone out of reach, sit somewhere comfortable, and be quiet with God for five minutes.",
    "whyItMatters": "You do not need any special words. Sitting quietly is one of the oldest ways people have made room for God.",
    "scriptureReference": "Psalm 46:10",
    "scriptureText": "“Be still, and know that I am God. I will be exalted among the nations. I will be exalted in the earth.”",
    "reflectionPrompt": "What rose to the surface in the quiet?",
    "prayerPrompt": "God, help me be still with you.",
    "growthType": "roots",
    "tags": [
      "stillness",
      "rest",
      "quiet"
    ],
    "seasonTags": [
      "ordinary_time",
      "advent"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "one-quiet-cup",
    "title": "One Quiet Cup",
    "category": "silence",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Drink one cup of coffee or tea today with no phone and no screen, just quiet.",
    "whyItMatters": "An unhurried cup is a small way of practicing presence — to your own life, and to the God who is present in it.",
    "scriptureReference": "Psalm 131:2",
    "scriptureText": "Surely I have stilled and quieted my soul, like a weaned child with his mother, like a weaned child is my soul within me.",
    "reflectionPrompt": "What was it like to do one ordinary thing slowly?",
    "prayerPrompt": "God, meet me in the small, quiet moments.",
    "growthType": "roots",
    "tags": [
      "morning",
      "rest",
      "attention"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "a-quiet-commute",
    "title": "A Quiet Commute",
    "category": "silence",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "On your next drive, ride, or walk between places, leave the music and podcasts off and let the time be quiet.",
    "whyItMatters": "The spaces between things are still part of the day God gave you. A quiet commute turns in-between time into open time.",
    "scriptureReference": "Isaiah 30:15",
    "scriptureText": "For thus said the Lord Yahweh, the Holy One of Israel, “You will be saved in returning and rest. Your strength will be in quietness and in confidence.” You refused,",
    "reflectionPrompt": "What did you notice once the noise was gone?",
    "prayerPrompt": "Lord, quiet me in the in-between places.",
    "growthType": "roots",
    "tags": [
      "commute",
      "quiet",
      "attention"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "listen-more-than-you-speak",
    "title": "Listen More Than You Speak",
    "category": "silence",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "In one conversation today, choose to listen more than you speak, and let the other person finish without hurry.",
    "whyItMatters": "Silence can be a gift we give. Listening well is a quiet form of love, and Scripture calls us to be quick to listen and slow to speak.",
    "scriptureReference": "James 1:19",
    "scriptureText": "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger;",
    "reflectionPrompt": "What did you learn by staying quiet a little longer?",
    "prayerPrompt": "Lord, teach me to listen the way you listen to me.",
    "growthType": "roots",
    "tags": [
      "listening",
      "conversation",
      "kindness"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "one-unplugged-hour",
    "title": "One Unplugged Hour",
    "category": "silence",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Set aside one hour today without your phone or screens, and let the quiet be unhurried.",
    "whyItMatters": "Jesus drew his friends away to quiet places to rest. An hour without noise is not lost time; it is room to breathe.",
    "scriptureReference": "Mark 6:31",
    "scriptureText": "He said to them, “You come apart into a deserted place, and rest awhile.” For there were many coming and going, and they had no leisure so much as to eat.",
    "reflectionPrompt": "What did you want to reach for, and what happened when you let it be?",
    "prayerPrompt": "Lord, be enough for me in the quiet.",
    "growthType": "roots",
    "tags": [
      "unplugged",
      "rest",
      "sabbath"
    ],
    "seasonTags": [
      "ordinary_time",
      "lent"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "discipline_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "watch-the-evening-sky",
    "title": "Watch the Evening Sky",
    "category": "silence",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "As the day ends, sit outside or by a window and watch the sky in silence for ten minutes.",
    "whyItMatters": "The sky has always drawn people toward wonder. Ending the day in quiet attention is a gentle way of remembering that your day rests in bigger hands than yours.",
    "scriptureReference": "Psalm 8:3-4",
    "scriptureText": "When I consider your heavens, the work of your fingers, the moon and the stars, which you have ordained; what is man, that you think of him? What is the son of man, that you care for him?",
    "reflectionPrompt": "What settled in you as you watched?",
    "prayerPrompt": "God, thank you for the wideness of this world and your care for me in it.",
    "growthType": "roots",
    "tags": [
      "evening",
      "creation",
      "wonder"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "read-one-psalm-slowly",
    "title": "Read One Psalm Slowly",
    "category": "scripture",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Read Psalm 23 slowly, twice, and let one phrase rest with you.",
    "whyItMatters": "Christians have returned to the psalms for thousands of years, especially when tired. Reading slowly turns words on a page into a place to rest.",
    "scriptureReference": "Psalm 23:1-6",
    "reflectionPrompt": "Which phrase stayed with you, and what might it be saying to you today?",
    "prayerPrompt": "Lord, be my shepherd today.",
    "growthType": "branches",
    "tags": [
      "psalms",
      "rest",
      "reading"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "carry-a-verse-through-your-afternoon",
    "title": "Carry a Verse Through Your Afternoon",
    "category": "scripture",
    "durationMinutes": 240,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Write one short verse where you will see it, and return to it whenever your afternoon pauses.",
    "whyItMatters": "Scripture is not only for quiet corners; it can walk with you through ordinary hours. A verse carried is a verse slowly learned by heart.",
    "scriptureReference": "Psalm 119:11",
    "scriptureText": "I have hidden your word in my heart, that I might not sin against you.",
    "reflectionPrompt": "When you returned to the verse, what did it sound like in the middle of your day?",
    "prayerPrompt": "Lord, keep your word close to me today.",
    "growthType": "branches",
    "tags": [
      "memory",
      "presence",
      "work"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "read-the-good-samaritan",
    "title": "Read the Good Samaritan",
    "category": "scripture",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Read the story of the Good Samaritan in Luke 10:25-37, a short story Jesus told about mercy, and notice who surprises you.",
    "whyItMatters": "This is one of the most loved stories Jesus ever told. It quietly reshapes how we see the people we pass.",
    "scriptureReference": "Luke 10:25-37",
    "reflectionPrompt": "Who in the story do you find yourself standing beside today?",
    "prayerPrompt": "Lord, teach me to be a neighbor.",
    "growthType": "branches",
    "tags": [
      "parables",
      "mercy",
      "neighbor"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "begin-a-gospel",
    "title": "Begin a Gospel",
    "category": "scripture",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Read the first chapter of Mark, the shortest account of Jesus's life, and simply notice what he does first.",
    "whyItMatters": "Every journey with Jesus begins somewhere. Mark's opening pages are a small, honest place to start, whoever you are.",
    "scriptureReference": "Mark 1:1-45",
    "reflectionPrompt": "What surprised you about how the story begins?",
    "prayerPrompt": "Lord, meet me at the beginning.",
    "growthType": "branches",
    "tags": [
      "gospels",
      "beginnings",
      "reading"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "read-the-beatitudes-outside",
    "title": "Read the Beatitudes Outside",
    "category": "scripture",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Take your Bible or phone somewhere outdoors and read the Beatitudes in Matthew 5:1-12 slowly, under the open sky.",
    "whyItMatters": "Jesus spoke these words on a hillside, in the open air. Hearing them outdoors can help them land as words for real life.",
    "scriptureReference": "Matthew 5:1-12",
    "reflectionPrompt": "Which blessing sounded most unlike the world you move through?",
    "prayerPrompt": "Lord, bless the parts of me the world overlooks.",
    "growthType": "branches",
    "tags": [
      "gospels",
      "outdoors",
      "blessing"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "one-verse-before-your-phone",
    "title": "One Verse Before Your Phone",
    "category": "scripture",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Before you scroll anything tonight, read one verse; Psalm 119:105 is a good place to begin.",
    "whyItMatters": "What we read first often sets the tone for everything after. One verse is a small way to let God's word have the first word.",
    "scriptureReference": "Psalm 119:105",
    "scriptureText": "Your word is a lamp to my feet, and a light for my path.",
    "reflectionPrompt": "How did the evening feel different when scripture came first?",
    "prayerPrompt": "Lord, let your word light my next step.",
    "growthType": "branches",
    "tags": [
      "evening",
      "phone",
      "habits"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [
      "discipline_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "look-back-on-your-day",
    "title": "Look Back on Your Day",
    "category": "reflection",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Sit comfortably, look back over your day from morning to now, and notice one moment where something good happened.",
    "whyItMatters": "Christians have long ended the day by looking back over it gently with God. Noticing is how gratitude begins.",
    "scriptureReference": "Psalm 139:23-24",
    "scriptureText": "Search me, God, and know my heart. Try me, and know my thoughts. See if there is any wicked way in me, and lead me in the everlasting way.",
    "reflectionPrompt": "Where in your day did you feel most alive, and where did you feel most drained?",
    "prayerPrompt": "Lord, thank you for walking through this day with me.",
    "growthType": "sunlight",
    "tags": [
      "evening",
      "gratitude",
      "noticing"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "name-what-you-are-carrying",
    "title": "Name What You Are Carrying",
    "category": "reflection",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Write down, in a few honest words, the worries you are carrying today, and read the list once to God.",
    "whyItMatters": "Naming a burden is often the first step toward handing it over. Scripture says we can cast our cares on God because he cares for us.",
    "scriptureReference": "1 Peter 5:7",
    "scriptureText": "casting all your worries on him, because he cares for you.",
    "reflectionPrompt": "Now that they have names, do any of these worries feel different?",
    "prayerPrompt": "Lord, I hand you what I cannot hold.",
    "growthType": "sunlight",
    "tags": [
      "anxiety",
      "honesty",
      "rest"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "notice-where-kindness-found-you",
    "title": "Notice Where Kindness Found You",
    "category": "reflection",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Think back over the past week and name one kindness someone showed you, however small.",
    "whyItMatters": "Kindness received is grace made visible. Remembering it turns an ordinary week into evidence of care.",
    "scriptureReference": "James 1:17",
    "scriptureText": "Every good gift and every perfect gift is from above, coming down from the Father of lights, with whom can be no variation, nor turning shadow.",
    "reflectionPrompt": "What does that kindness tell you about how God might be caring for you?",
    "prayerPrompt": "Lord, thank you for the hands that carried kindness to me.",
    "growthType": "sunlight",
    "tags": [
      "gratitude",
      "memory",
      "kindness"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "a-walk-without-headphones",
    "title": "A Walk Without Headphones",
    "category": "reflection",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Take a short walk without headphones and let what you see and hear become your reflection.",
    "whyItMatters": "Creation has its own quiet way of speaking. Walking unplugged makes room to notice what usually goes unheard.",
    "scriptureReference": "Psalm 19:1",
    "scriptureText": "The heavens declare the glory of God. The expanse shows his handiwork.",
    "reflectionPrompt": "What did you notice on your walk that you would normally miss?",
    "prayerPrompt": "Lord, open my eyes to what you have made.",
    "growthType": "sunlight",
    "tags": [
      "outdoors",
      "noticing",
      "quiet"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "release-one-old-hurt",
    "title": "Release One Old Hurt",
    "category": "reflection",
    "durationMinutes": 15,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "In a quiet moment, name one old hurt to God and ask for his help to loosen your grip on it; nothing more is asked of you today.",
    "whyItMatters": "Forgiveness is a journey that begins inside, long before anything else. Even the willingness to release is a step.",
    "scriptureReference": "Ephesians 4:31-32",
    "scriptureText": "Let all bitterness, wrath, anger, outcry, and slander be put away from you, with all malice. And be kind to one another, tender hearted, forgiving each other, just as God also in Christ forgave you.",
    "reflectionPrompt": "What might your heart feel like with a little less of this weight?",
    "prayerPrompt": "Lord, help me release what I have carried too long.",
    "growthType": "sunlight",
    "tags": [
      "forgiveness",
      "healing",
      "peace"
    ],
    "seasonTags": [
      "ordinary_time",
      "lent"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive",
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "write-your-own-psalm",
    "title": "Write Your Own Psalm",
    "category": "reflection",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Set aside an unhurried hour to write an honest prayer in your own words — your joys, your questions, your hopes — the way the psalmists did.",
    "whyItMatters": "The psalms show that God welcomes honest words, not polished ones. Writing your own is a way of pouring out your heart.",
    "scriptureReference": "Psalm 62:8",
    "scriptureText": "Trust in him at all times, you people. Pour out your heart before him. God is a refuge for us.",
    "reflectionPrompt": "What was it like to say to God exactly what you meant?",
    "prayerPrompt": "Lord, receive my honest words.",
    "growthType": "sunlight",
    "tags": [
      "writing",
      "psalms",
      "honesty"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "send-a-kind-word",
    "title": "Send a Kind Word",
    "category": "kindness",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Send one honest, kind message to someone who comes to mind today.",
    "whyItMatters": "A few true words can carry more weight than we know. Kindness often begins this small.",
    "scriptureReference": "Ephesians 4:29",
    "scriptureText": "Let no corrupt speech proceed out of your mouth, but only what is good for building others up as the need may be, that it may give grace to those who hear.",
    "reflectionPrompt": "Who came to mind first, and why do you think it was them?",
    "prayerPrompt": "God, give me words that are gentle and true.",
    "growthType": "leaves",
    "tags": [
      "encouragement",
      "friendship",
      "words"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "let-someone-go-first",
    "title": "Let Someone Go First",
    "category": "kindness",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Once today, let someone go ahead of you — in line, in traffic, or through a door — and mean it.",
    "whyItMatters": "Yielding a small place is a quiet way of honoring another person. It loosens the grip of hurry.",
    "scriptureReference": "Philippians 2:3-4",
    "scriptureText": "doing nothing through rivalry or through conceit, but in humility, each counting others better than himself; each of you not just looking to his own things, but each of you also to the things of others.",
    "reflectionPrompt": "What did it feel like to slow down and make room for someone?",
    "prayerPrompt": "God, teach me to make room for others.",
    "growthType": "leaves",
    "tags": [
      "patience",
      "humility",
      "everyday"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "thank-someone-who-serves-you",
    "title": "Thank Someone Who Serves You",
    "category": "kindness",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Thank someone who serves you today — a cashier, a driver, a coworker — slowly enough that they know you mean it.",
    "whyItMatters": "Gratitude turns a transaction into a meeting between two people. Kindness notices the ones who are easy to overlook.",
    "scriptureReference": "Colossians 3:12",
    "scriptureText": "Put on therefore, as God’s chosen ones, holy and beloved, a heart of compassion, kindness, lowliness, humility, and perseverance;",
    "reflectionPrompt": "Whom do you pass most days without really seeing?",
    "prayerPrompt": "Lord, open my eyes to the people I usually hurry past.",
    "growthType": "leaves",
    "tags": [
      "gratitude",
      "strangers",
      "everyday"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "speak-gently-to-yourself",
    "title": "Speak Gently to Yourself",
    "category": "kindness",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "When you catch a harsh thought about yourself today, answer it the way you would answer a tired friend.",
    "whyItMatters": "God is gentler with us than we are with ourselves. Practicing that gentleness is not indulgence; it is trust.",
    "scriptureReference": "Psalm 103:13-14",
    "scriptureText": "Like a father has compassion on his children, so Yahweh has compassion on those who fear him. For he knows how we are made. He remembers that we are dust.",
    "reflectionPrompt": "What would change if you believed God looks at you with compassion?",
    "prayerPrompt": "God, help me receive the same mercy I hope to give.",
    "growthType": "leaves",
    "tags": [
      "self-compassion",
      "rest",
      "mercy"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "write-an-unhurried-note",
    "title": "Write an Unhurried Note",
    "category": "kindness",
    "durationMinutes": 15,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Handwrite a short note of thanks or encouragement and leave it where the right person will find it.",
    "whyItMatters": "A written word lasts longer than a spoken one. It says: I stopped, and I thought of you.",
    "scriptureReference": "Hebrews 10:24",
    "scriptureText": "Let’s consider how to provoke one another to love and good works,",
    "reflectionPrompt": "What made you choose the person you wrote to?",
    "prayerPrompt": "Lord, let my words build someone up today.",
    "growthType": "leaves",
    "tags": [
      "encouragement",
      "writing",
      "gratitude"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "carry-kindness-through-the-afternoon",
    "title": "Carry Kindness Through the Afternoon",
    "category": "kindness",
    "durationMinutes": 240,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "Carry one quiet intention through your afternoon: when small exchanges come — a checkout line, a hallway, a reply — meet them with kindness, without announcing it.",
    "whyItMatters": "Kindness practiced in secret shapes us more than kindness performed. The afternoon offers dozens of small doors.",
    "scriptureReference": "Micah 6:8",
    "scriptureText": "He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?",
    "reflectionPrompt": "Where did kindness come easily today, and where did it cost you something?",
    "prayerPrompt": "Lord, keep me kind when no one is watching.",
    "growthType": "leaves",
    "tags": [
      "intention",
      "mercy",
      "everyday"
    ],
    "seasonTags": [
      "ordinary_time",
      "lent"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "pray-for-your-neighbors",
    "title": "Pray for Your Neighbors",
    "category": "community",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "From wherever you are sitting, pray for your neighbors — house by house, door by door, as far as you know them.",
    "whyItMatters": "Scripture asks God's people to seek the good of the place they live. Prayer is how that seeking begins.",
    "scriptureReference": "Jeremiah 29:7",
    "scriptureText": "Seek the peace of the city where I have caused you to be carried away captive, and pray to Yahweh for it; for in its peace you will have peace.”",
    "reflectionPrompt": "Which neighbor stayed on your mind after you finished?",
    "prayerPrompt": "Lord, bless the people who live near me, whether or not I know their names.",
    "growthType": "roots",
    "tags": [
      "prayer",
      "neighbors",
      "home"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "learn-a-neighbors-name",
    "title": "Learn a Neighbor's Name",
    "category": "community",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Greet one neighbor today and learn their name — or use the name you already know, warmly.",
    "whyItMatters": "Loving a neighbor starts with knowing one. A name is a small door into care.",
    "scriptureReference": "Mark 12:31",
    "scriptureText": "The second is like this, ‘You shall love your neighbor as yourself.’ There is no other commandment greater than these.”",
    "reflectionPrompt": "How did it change the moment when you used their name?",
    "prayerPrompt": "God, help me see the people who live beside me.",
    "growthType": "leaves",
    "tags": [
      "neighbors",
      "hospitality",
      "courage"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "check-in-on-an-old-friend",
    "title": "Check In on an Old Friend",
    "category": "community",
    "durationMinutes": 10,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Send a simple message to a friend you have quietly drifted from — no agenda, just to say you thought of them.",
    "whyItMatters": "Friendships fade quietly, and they can be rekindled quietly too. Bearing one another's burdens begins with showing up.",
    "scriptureReference": "Galatians 6:2",
    "scriptureText": "Bear one another’s burdens, and so fulfill the law of Christ.",
    "reflectionPrompt": "What do you miss about this friendship?",
    "prayerPrompt": "Lord, thank you for the people who have walked part of the road with me.",
    "growthType": "leaves",
    "tags": [
      "friendship",
      "connection",
      "faithfulness"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "share-a-meal-with-someone",
    "title": "Share a Meal with Someone",
    "category": "community",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Invite someone to share a simple meal or a cup of coffee with you, today if you can. Your own table, and whatever you already have, is enough.",
    "whyItMatters": "The early church grew around ordinary tables. Something in us opens when we eat together.",
    "scriptureReference": "Acts 2:46",
    "scriptureText": "Day by day, continuing steadfastly with one accord in the temple, and breaking bread at home, they took their food with gladness and singleness of heart,",
    "reflectionPrompt": "What came up in the conversation that would not have come up in passing?",
    "prayerPrompt": "Lord, make my table a welcoming place.",
    "growthType": "fruit",
    "tags": [
      "hospitality",
      "meals",
      "fellowship"
    ],
    "seasonTags": [
      "ordinary_time",
      "easter"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "ask-an-elder-for-a-story",
    "title": "Ask an Elder for a Story",
    "category": "community",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Call or sit with an older person you trust and ask them to tell you a story from their life.",
    "whyItMatters": "Listening honors a life. The church has always believed the old and the young need each other.",
    "scriptureReference": "Job 12:12",
    "scriptureText": "With aged men is wisdom, in length of days understanding.",
    "reflectionPrompt": "What did their story teach you that you could not have learned alone?",
    "prayerPrompt": "Lord, thank you for the long faithfulness of those who walked before me.",
    "growthType": "leaves",
    "tags": [
      "listening",
      "elders",
      "stories"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "bless-the-room",
    "title": "Bless the Room",
    "category": "community",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Wherever people gather around you today, silently ask God to bless each person you can see.",
    "whyItMatters": "A hidden blessing changes the one who prays it. Strangers become neighbors in the quiet of the heart.",
    "scriptureReference": "Numbers 6:24-26",
    "scriptureText": "‘Yahweh bless you, and keep you. Yahweh make his face to shine on you, and be gracious to you. Yahweh lift up his face toward you, and give you peace.’",
    "reflectionPrompt": "How did the room feel different once you had prayed for the people in it?",
    "prayerPrompt": "God, bless each person near me today, in the ways they need most.",
    "growthType": "roots",
    "tags": [
      "prayer",
      "strangers",
      "presence"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "carry-someones-load",
    "title": "Carry Someone's Load",
    "category": "service",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Quietly take on one small task today that usually belongs to someone else, like the dishes, the trash, or tidying a shared space.",
    "whyItMatters": "When we carry a small piece of someone else's day, we practice the love Christ asks of us. It is ordinary work, and that is exactly where love lives.",
    "scriptureReference": "Galatians 6:2",
    "scriptureText": "Bear one another’s burdens, and so fulfill the law of Christ.",
    "reflectionPrompt": "What did you notice about the person whose load you carried?",
    "prayerPrompt": "God, teach me to see the small burdens I can carry for others.",
    "growthType": "fruit",
    "tags": [
      "home",
      "humility",
      "helping"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "serve-without-being-seen",
    "title": "Serve Without Being Seen",
    "category": "service",
    "durationMinutes": 15,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Do one helpful thing today that no one will know you did, like tidying a shared space, refilling what has run out, or picking up stray litter, and keep it between you and God.",
    "whyItMatters": "Hidden service frees us from performing. Work done quietly, as for the Lord, shapes the heart more than work done for applause.",
    "scriptureReference": "Colossians 3:23",
    "scriptureText": "And whatever you do, work heartily, as for the Lord, and not for men,",
    "reflectionPrompt": "How did it feel to help without anyone knowing?",
    "prayerPrompt": "Lord, let me be content to serve where only you can see.",
    "growthType": "fruit",
    "tags": [
      "humility",
      "quiet",
      "hidden service"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "make-way-for-a-stranger",
    "title": "Make Way for a Stranger",
    "category": "service",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "While you are out today, offer one small courtesy to a stranger, like returning a cart, holding a door, or letting someone go ahead of you.",
    "whyItMatters": "Jesus taught that small kindnesses to ordinary people are kindnesses to him. A five-second courtesy can be a quiet act of faith.",
    "scriptureReference": "Matthew 25:40",
    "scriptureText": "“The King will answer them, ‘Most certainly I tell you, because you did it to one of the least of these my brothers, you did it to me.’",
    "reflectionPrompt": "Who crossed your path today that you might otherwise have overlooked?",
    "prayerPrompt": "God, help me notice the people in front of me.",
    "growthType": "fruit",
    "tags": [
      "strangers",
      "errands",
      "courtesy"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "lend-a-hand-at-work",
    "title": "Lend a Hand at Work",
    "category": "service",
    "durationMinutes": 15,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Notice one task a coworker or classmate is carrying today, and offer fifteen minutes of real help with it.",
    "whyItMatters": "Faith is not only for quiet mornings; it walks into workplaces too. Looking to the interests of others turns an ordinary Tuesday into a place of grace.",
    "scriptureReference": "Philippians 2:4",
    "scriptureText": "each of you not just looking to his own things, but each of you also to the things of others.",
    "reflectionPrompt": "What changed between you and the person you helped?",
    "prayerPrompt": "Lord, make my work a way of loving the people around me.",
    "growthType": "fruit",
    "tags": [
      "work",
      "helping",
      "colleagues"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "one-hour-given",
    "title": "One Hour, Given",
    "category": "service",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "Set aside one unhurried hour today to serve someone, perhaps helping a neighbor, preparing a meal for a tired friend, or caring for a shared space.",
    "whyItMatters": "Jesus described his own life as one of service, not of being served. Giving a whole hour, without rushing, lets us walk a small stretch of that same road.",
    "scriptureReference": "Mark 10:45",
    "scriptureText": "For the Son of Man also came not to be served, but to serve, and to give his life as a ransom for many.”",
    "reflectionPrompt": "Where did you sense God during the hour you gave away?",
    "prayerPrompt": "Lord, let this hour belong to someone other than me.",
    "growthType": "fruit",
    "tags": [
      "neighbors",
      "time",
      "helping"
    ],
    "seasonTags": [
      "ordinary_time",
      "lent"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "ask-what-someone-needs",
    "title": "Ask What Someone Needs",
    "category": "service",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Send one honest message to someone in your life asking what you could do to make their week a little lighter.",
    "whyItMatters": "Service begins with asking, not assuming. Even from the couch, on a tired day, one question can open a door for love.",
    "scriptureReference": "Galatians 5:13",
    "scriptureText": "For you, brothers, were called for freedom. Only don’t use your freedom for gain to the flesh, but through love be servants to one another.",
    "reflectionPrompt": "What did it feel like to ask instead of assuming you already knew?",
    "prayerPrompt": "God, give me the humility to ask and the willingness to follow through.",
    "growthType": "fruit",
    "tags": [
      "listening",
      "friends",
      "low energy"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "set-something-aside-to-give",
    "title": "Set Something Aside to Give",
    "category": "generosity",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Choose one thing you own that is in good condition, and set it aside today to pass along to someone who could use it.",
    "whyItMatters": "Loosening our grip on one possession is a small rehearsal of trust. Giving reminds us that what we hold was first given to us.",
    "scriptureReference": "Acts 20:35",
    "scriptureText": "In all things I gave you an example, that so laboring you ought to help the weak, and to remember the words of the Lord Jesus, that he himself said, ‘It is more blessed to give than to receive.’”",
    "reflectionPrompt": "What was it like to let go of something you own?",
    "prayerPrompt": "Lord, loosen my hands so that good things can pass through them.",
    "growthType": "fruit",
    "tags": [
      "giving",
      "possessions",
      "simplicity"
    ],
    "seasonTags": [
      "ordinary_time",
      "advent"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "money_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "a-quiet-gift",
    "title": "A Quiet Gift",
    "category": "generosity",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "If it is within your means, give a small gift today to a cause or person you trust, and tell no one about it.",
    "whyItMatters": "Jesus invited his followers to give in secret, where generosity stays honest. The size of the gift matters far less than the quiet of the heart behind it.",
    "scriptureReference": "Matthew 6:3-4",
    "scriptureText": "But when you do merciful deeds, don’t let your left hand know what your right hand does, so that your merciful deeds may be in secret, then your Father who sees in secret will reward you openly.",
    "reflectionPrompt": "What did giving in secret free you from?",
    "prayerPrompt": "God, let my giving be simple, quiet, and glad.",
    "growthType": "fruit",
    "tags": [
      "giving",
      "secrecy",
      "trust"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "money_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "give-your-full-attention",
    "title": "Give Your Full Attention",
    "category": "generosity",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Give one person your whole attention today for fifteen minutes, with your phone out of reach and no hurry to speak.",
    "whyItMatters": "Attention may be the most generous thing we can give. Listening well is a way of saying: you matter, and I am not in a rush.",
    "scriptureReference": "James 1:19",
    "scriptureText": "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger;",
    "reflectionPrompt": "What did you hear that you might have missed on an ordinary day?",
    "prayerPrompt": "God, quiet my hurry so I can truly listen.",
    "growthType": "fruit",
    "tags": [
      "listening",
      "presence",
      "attention"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "ten-minutes-for-someone-lonely",
    "title": "Ten Minutes for Someone Lonely",
    "category": "generosity",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Call or message someone who may be lonely today, and give them ten unhurried minutes of your company.",
    "whyItMatters": "Time is a gift we rarely think to give. A short call can remind someone they are held in affection, and remind us that love is often this simple.",
    "scriptureReference": "Romans 12:10",
    "scriptureText": "In love of the brothers be tenderly affectionate to one another; in honor preferring one another;",
    "reflectionPrompt": "How did the conversation change the shape of your day?",
    "prayerPrompt": "Lord, bring to mind the person who needs company today.",
    "growthType": "fruit",
    "tags": [
      "loneliness",
      "time",
      "connection"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "share-what-you-have",
    "title": "Share What You Have",
    "category": "generosity",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Share something you already have today, like a meal, a cup of coffee, a book, or the extra portion you made, with someone nearby.",
    "whyItMatters": "Scripture calls sharing a kind of offering. We do not need more in order to be generous; we only need open hands with what is already ours.",
    "scriptureReference": "Hebrews 13:16",
    "scriptureText": "But don’t forget to be doing good and sharing, for with such sacrifices God is well pleased.",
    "reflectionPrompt": "What do you already have that seems meant to be shared?",
    "prayerPrompt": "God, show me what in my hands is meant for someone else.",
    "growthType": "fruit",
    "tags": [
      "sharing",
      "food",
      "hospitality"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "open-hands-through-the-afternoon",
    "title": "Open Hands Through the Afternoon",
    "category": "generosity",
    "durationMinutes": 240,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "Begin your afternoon with a short prayer of open hands, then watch for one small chance to give a little time, attention, or help before the evening comes.",
    "whyItMatters": "Generosity is a posture before it is an act. Holding the day loosely, we begin to give the way God loves: freely and gladly.",
    "scriptureReference": "2 Corinthians 9:7",
    "scriptureText": "Let each man give according as he has determined in his heart, not grudgingly or under compulsion, for God loves a cheerful giver.",
    "reflectionPrompt": "Where did an open hand find something to do this afternoon?",
    "prayerPrompt": "Lord, keep my hands open through the ordinary hours of this day.",
    "growthType": "fruit",
    "tags": [
      "intention",
      "awareness",
      "giving"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "name-the-weight",
    "title": "Name the Weight",
    "category": "forgiveness",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Sit somewhere quiet and name, honestly and without hurry, one hurt you are still carrying.",
    "whyItMatters": "We cannot release what we have not named. Bringing a hurt into the light before God is the quiet beginning of forgiveness.",
    "scriptureReference": "Psalm 55:22",
    "scriptureText": "Cast your burden on Yahweh and he will sustain you. He will never allow the righteous to be moved.",
    "reflectionPrompt": "What did it feel like to say the hurt out loud, even just to God?",
    "prayerPrompt": "Lord, I hand you this weight; help me carry it no longer alone.",
    "growthType": "roots",
    "tags": [
      "prayer",
      "release",
      "honesty"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "write-an-unsent-letter",
    "title": "Write an Unsent Letter",
    "category": "forgiveness",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Write a letter you will never send to someone who hurt you, saying everything you need to say, then set it aside or tear it up.",
    "whyItMatters": "The page can hold what the heart has carried too long. Forgiveness often begins as private, honest work between you and God.",
    "scriptureReference": "Ephesians 4:31-32",
    "scriptureText": "Let all bitterness, wrath, anger, outcry, and slander be put away from you, with all malice. And be kind to one another, tender hearted, forgiving each other, just as God also in Christ forgave you.",
    "reflectionPrompt": "What surprised you as the words came out?",
    "prayerPrompt": "God of mercy, receive what I have written and begin to soften what is hard in me.",
    "growthType": "sunlight",
    "tags": [
      "writing",
      "release",
      "bitterness"
    ],
    "seasonTags": [
      "ordinary_time",
      "lent"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive",
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "pray-for-someone-hard-to-love-2",
    "title": "Pray for Someone Hard to Love",
    "category": "forgiveness",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Pray one honest sentence today for a person you find hard to love.",
    "whyItMatters": "Jesus asked his friends to pray for the people who hurt them. Prayer does not excuse the wrong; it loosens its grip on us.",
    "scriptureReference": "Matthew 5:44",
    "scriptureText": "But I tell you, love your enemies, bless those who curse you, do good to those who hate you, and pray for those who mistreat you and persecute you,",
    "reflectionPrompt": "What was it like to bring that name into prayer?",
    "prayerPrompt": "Lord, bless them, and free my heart from what I hold against them.",
    "growthType": "roots",
    "tags": [
      "prayer",
      "mercy",
      "release"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive",
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "open-your-hands",
    "title": "Open Your Hands",
    "category": "forgiveness",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Sit with your fists gently closed, name an old hurt, then slowly open your hands as a small sign of letting go.",
    "whyItMatters": "Sometimes the body can pray what words cannot. Opening your hands is a quiet way of asking God to take what you cannot keep carrying.",
    "scriptureReference": "Colossians 3:13",
    "scriptureText": "bearing with one another, and forgiving each other, if any man has a complaint against any; even as Christ forgave you, so you also do.",
    "reflectionPrompt": "What are you still holding, and what would it mean to loosen your grip a little?",
    "prayerPrompt": "God, I open my hands; take what I have been holding too tightly.",
    "growthType": "roots",
    "tags": [
      "prayer",
      "body",
      "release"
    ],
    "seasonTags": [
      "ordinary_time",
      "lent"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "forgive-yourself-one-thing",
    "title": "Forgive Yourself One Thing",
    "category": "forgiveness",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Name one thing you still hold against yourself. Then read Psalm 103:12 slowly, and hear it spoken over that very thing.",
    "whyItMatters": "Many of us extend to others a mercy we refuse ourselves. Receiving forgiveness is part of learning to give it.",
    "scriptureReference": "Psalm 103:12",
    "scriptureText": "As far as the east is from the west, so far has he removed our transgressions from us.",
    "reflectionPrompt": "Why is it hard to let yourself be forgiven?",
    "prayerPrompt": "Lord, you have let this go; help me let it go too.",
    "growthType": "sunlight",
    "tags": [
      "mercy",
      "self-compassion",
      "grace"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "walk-and-release",
    "title": "Walk and Release",
    "category": "forgiveness",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Take a slow walk, and with each stretch of the way, quietly ask God to loosen one old hurt you have carried.",
    "whyItMatters": "Pilgrims have always prayed with their feet. A walk gives grief and grievance somewhere to go.",
    "scriptureReference": "Psalm 147:3",
    "scriptureText": "He heals the broken in heart, and binds up their wounds.",
    "reflectionPrompt": "Did the hurt feel any lighter by the end of the walk, even slightly?",
    "prayerPrompt": "Healer of hearts, walk with me and teach me how to let this go.",
    "growthType": "roots",
    "tags": [
      "walking",
      "release",
      "healing"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive",
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "let-someone-go-first-2",
    "title": "Let Someone Go First",
    "category": "patience",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "The next time you are in a line or in traffic today, let someone go ahead of you without hurry or announcement.",
    "whyItMatters": "Patience becomes real in small surrenders. Yielding a place is a quiet way of honoring another person.",
    "scriptureReference": "Philippians 2:3",
    "scriptureText": "doing nothing through rivalry or through conceit, but in humility, each counting others better than himself;",
    "reflectionPrompt": "What rose up in you when you chose to wait?",
    "prayerPrompt": "God, teach me to make room for others with a glad heart.",
    "growthType": "leaves",
    "tags": [
      "yielding",
      "errands",
      "humility"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "wait-without-your-phone",
    "title": "Wait Without Your Phone",
    "category": "patience",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "The next time you find yourself waiting today, leave your phone in your pocket and let the waiting be quiet.",
    "whyItMatters": "Waiting is one of the oldest schools of the soul. Small empty moments can become small open ones.",
    "scriptureReference": "Psalm 27:14",
    "scriptureText": "Wait for Yahweh. Be strong, and let your heart take courage. Yes, wait for Yahweh.",
    "reflectionPrompt": "What did you notice in the quiet that you usually miss?",
    "prayerPrompt": "God, meet me in the waiting.",
    "growthType": "leaves",
    "tags": [
      "waiting",
      "stillness",
      "attention"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [
      "discipline_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "listen-without-interrupting",
    "title": "Listen Without Interrupting",
    "category": "patience",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "In one conversation today, let the other person finish everything they want to say before you speak.",
    "whyItMatters": "Listening well is patience with a face. It tells another person their words are worth your time.",
    "scriptureReference": "James 1:19",
    "scriptureText": "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger;",
    "reflectionPrompt": "What did you hear that you might have missed?",
    "prayerPrompt": "Lord, slow my tongue and open my ears.",
    "growthType": "leaves",
    "tags": [
      "listening",
      "conversation",
      "presence"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "carry-patience-through-the-afternoon",
    "title": "Carry Patience Through the Afternoon",
    "category": "patience",
    "durationMinutes": 240,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "Choose the words 'slow to anger, rich in mercy' and return to them gently each time you have to wait this afternoon.",
    "whyItMatters": "Patience grows less by effort than by remembering who God is. A phrase carried through ordinary hours can slowly change their weather.",
    "scriptureReference": "Psalm 103:8",
    "scriptureText": "Yahweh is merciful and gracious, slow to anger, and abundant in loving kindness.",
    "reflectionPrompt": "When was it hardest to return to the words, and what helped you come back?",
    "prayerPrompt": "Lord, slow to anger and rich in mercy, shape my afternoon.",
    "growthType": "leaves",
    "tags": [
      "waiting",
      "daily-life",
      "mercy"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "be-patient-with-yourself",
    "title": "Be Patient With Yourself",
    "category": "patience",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Wherever you are right now, take three slow breaths, then say one kind and true sentence to yourself, as gently as God speaks to the weary.",
    "whyItMatters": "God's compassion covers the tired and the unfinished. Being gentle with yourself is not weakness; it is trust.",
    "scriptureReference": "Psalm 103:13-14",
    "scriptureText": "Like a father has compassion on his children, so Yahweh has compassion on those who fear him. For he knows how we are made. He remembers that we are dust.",
    "reflectionPrompt": "Where have you been hardest on yourself lately?",
    "prayerPrompt": "God, you know what I am made of; be gentle with me, and help me be gentle too.",
    "growthType": "sunlight",
    "tags": [
      "rest",
      "self-compassion",
      "gentleness"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "one-unhurried-hour",
    "title": "One Unhurried Hour",
    "category": "patience",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Choose one hour today and move through it at an unhurried pace, doing whatever it holds without rushing.",
    "whyItMatters": "Hurry is a habit, and so is peace. One slow hour teaches the body what the heart already suspects: most things can wait.",
    "scriptureReference": "Ecclesiastes 3:1",
    "scriptureText": "For everything there is a season, and a time for every purpose under heaven:",
    "reflectionPrompt": "What felt different when you stopped rushing?",
    "prayerPrompt": "Lord of all seasons, teach me an unhurried heart.",
    "growthType": "leaves",
    "tags": [
      "slowness",
      "rest",
      "daily-life"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "three-small-thanks",
    "title": "Three Small Thanks",
    "category": "gratitude",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Before the day ends, name three small things you are thankful for.",
    "whyItMatters": "Gratitude begins with noticing. Naming small gifts is an old and simple way of returning to God.",
    "scriptureReference": "1 Thessalonians 5:18",
    "scriptureText": "In everything give thanks, for this is the will of God in Christ Jesus toward you.",
    "reflectionPrompt": "Which of the three surprised you?",
    "prayerPrompt": "Thank you, God, for the small gifts I almost missed.",
    "growthType": "flowers",
    "tags": [
      "noticing",
      "thankfulness",
      "evening"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "thank-someone-who-helped-you",
    "title": "Thank Someone Who Helped You",
    "category": "gratitude",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Send a short, honest thank-you to someone — a friend, a relative, a coworker — whose help you never fully acknowledged.",
    "whyItMatters": "Gratitude grows when it is spoken. A simple thank-you honors the way God cares for us through other people.",
    "scriptureReference": "Philippians 1:3",
    "scriptureText": "I thank my God whenever I remember you,",
    "reflectionPrompt": "What changed in you when you put your thanks into words?",
    "prayerPrompt": "Lord, thank you for the people you have placed in my life.",
    "growthType": "flowers",
    "tags": [
      "thankfulness",
      "relationships",
      "encouragement"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "grace-before-one-meal",
    "title": "Grace Before One Meal",
    "category": "gratitude",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "indoor",
    "invitation": "Before one meal today, pause and quietly give thanks for the food in front of you.",
    "whyItMatters": "Pausing before we eat is one of the oldest Christian habits. It turns an ordinary meal into a small act of gratitude.",
    "scriptureReference": "1 Timothy 4:4-5",
    "scriptureText": "For every creature of God is good, and nothing is to be rejected, if it is received with thanksgiving. For it is sanctified through the word of God and prayer.",
    "reflectionPrompt": "How did the meal feel different after you paused?",
    "prayerPrompt": "Thank you, God, for this food and for every hand that brought it to me.",
    "growthType": "flowers",
    "tags": [
      "meals",
      "thankfulness",
      "home"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "carry-gratitude-through-the-afternoon",
    "title": "Carry Gratitude Through the Afternoon",
    "category": "gratitude",
    "durationMinutes": 240,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Carry one quiet intention through your afternoon: whenever a small gift comes — warm light, a kind word, a task finished — pause and thank God for it in silence.",
    "whyItMatters": "Gratitude is not only a moment but a way of walking through the day. Noticing is how thankfulness becomes a habit of the heart.",
    "scriptureReference": "Psalm 118:24",
    "scriptureText": "This is the day that Yahweh has made. We will rejoice and be glad in it!",
    "reflectionPrompt": "What did you notice this afternoon that you would usually walk past?",
    "prayerPrompt": "God, open my eyes to the gifts in this day.",
    "growthType": "flowers",
    "tags": [
      "noticing",
      "presence",
      "daily-life"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "a-walk-of-noticing",
    "title": "A Walk of Noticing",
    "category": "gratitude",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Take a slow walk and quietly thank God for what you see along the way.",
    "whyItMatters": "Creation has always led people to gratitude. A slow walk gives thankfulness room to breathe.",
    "scriptureReference": "Psalm 19:1",
    "scriptureText": "The heavens declare the glory of God. The expanse shows his handiwork.",
    "reflectionPrompt": "What did you see today that felt like a gift?",
    "prayerPrompt": "Thank you, Lord, for the world you have made.",
    "growthType": "flowers",
    "tags": [
      "creation",
      "walking",
      "noticing"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "thanks-after-a-hard-season",
    "title": "Thanks After a Hard Season",
    "category": "gratitude",
    "durationMinutes": 15,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Write a few honest lines about a hard season, and gently name one small mercy that carried you through it. If no mercy comes to mind yet, write that too; honesty is its own prayer.",
    "whyItMatters": "Gratitude does not deny sorrow; it looks for the mercy inside it. This is slow work, and it cannot be rushed.",
    "scriptureReference": "Lamentations 3:22-23",
    "scriptureText": "It is because of Yahweh’s loving kindnesses that we are not consumed, because his compassion doesn’t fail. They are new every morning. Great is your faithfulness.",
    "reflectionPrompt": "Looking back, what do you see now that you could not see at the time?",
    "prayerPrompt": "Lord, thank you for staying near me in the hard days.",
    "growthType": "sunlight",
    "tags": [
      "healing",
      "reflection",
      "mercy"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "sing-one-song",
    "title": "Sing One Song",
    "category": "worship",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Play or quietly sing one song that turns your heart toward God, and give it your whole attention from beginning to end.",
    "whyItMatters": "Music is one of the oldest ways people have reached toward God. One song, honestly attended to, is enough.",
    "scriptureReference": "Psalm 95:1",
    "scriptureText": "Oh come, let’s sing to Yahweh. Let’s shout aloud to the rock of our salvation!",
    "reflectionPrompt": "What line stayed with you after the song ended?",
    "prayerPrompt": "God, receive this song as my thanks and my praise.",
    "growthType": "flowers",
    "tags": [
      "music",
      "praise",
      "quiet"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "pray-a-psalm-of-praise",
    "title": "Pray a Psalm of Praise",
    "category": "worship",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Read Psalm 100 slowly, and let its words become your own prayer.",
    "whyItMatters": "The psalms have carried the church's worship for thousands of years. Praying one joins your voice to that long song.",
    "scriptureReference": "Psalm 100:1-2",
    "scriptureText": "Shout for joy to Yahweh, all you lands! Serve Yahweh with gladness. Come before his presence with singing.",
    "reflectionPrompt": "Which word of the psalm felt most like your own?",
    "prayerPrompt": "Lord, teach me to praise you with words older than my own.",
    "growthType": "branches",
    "tags": [
      "psalms",
      "scripture",
      "praise"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "worship-in-the-ordinary",
    "title": "Worship in the Ordinary",
    "category": "worship",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Choose one ordinary task today — dishes, a letter, a chore — and do it slowly, as a quiet offering to God.",
    "whyItMatters": "Worship is not confined to Sunday mornings. Ordinary work, done with love and attention, can be offered to God.",
    "scriptureReference": "Colossians 3:17",
    "scriptureText": "Whatever you do, in word or in deed, do all in the name of the Lord Jesus, giving thanks to God the Father, through him.",
    "reflectionPrompt": "How did the task change when you offered it to God?",
    "prayerPrompt": "Lord, let my ordinary work be a gift to you.",
    "growthType": "flowers",
    "tags": [
      "work",
      "daily-life",
      "offering"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "five-minutes-of-praise",
    "title": "Five Minutes of Praise",
    "category": "worship",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Spend five minutes telling God who he is, without asking for anything.",
    "whyItMatters": "Praise sets our requests aside for a moment. It rests the heart on God rather than on our needs.",
    "scriptureReference": "Psalm 145:3",
    "scriptureText": "Great is Yahweh, and greatly to be praised! His greatness is unsearchable.",
    "reflectionPrompt": "What was it like to pray without asking?",
    "prayerPrompt": "God, you are good, and I simply want to say so.",
    "growthType": "flowers",
    "tags": [
      "praise",
      "prayer",
      "quiet"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "step-outside-and-look-up",
    "title": "Step Outside and Look Up",
    "category": "worship",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Step outside, look up at the sky for a few minutes, and let whatever wonder you feel turn quietly toward God.",
    "whyItMatters": "You do not need special words to worship. Wonder, honestly felt, is already a beginning.",
    "scriptureReference": "Psalm 8:3-4",
    "scriptureText": "When I consider your heavens, the work of your fingers, the moon and the stars, which you have ordained; what is man, that you think of him? What is the son of man, that you care for him?",
    "reflectionPrompt": "What did the sky stir in you?",
    "prayerPrompt": "God, the world you made is beyond me, and I am glad.",
    "growthType": "flowers",
    "tags": [
      "creation",
      "wonder",
      "outdoors"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "an-hour-set-apart",
    "title": "An Hour Set Apart",
    "category": "worship",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Set apart one quiet hour today for God — some scripture, some music, some silence, and no agenda.",
    "whyItMatters": "Unhurried time is its own form of praise. An hour given freely says, more than words, that God is worth our attention.",
    "scriptureReference": "Psalm 27:4",
    "scriptureText": "One thing I have asked of Yahweh, that I will seek after: that I may dwell in Yahweh’s house all the days of my life, to see Yahweh’s beauty, and to inquire in his temple.",
    "reflectionPrompt": "What rose in you when the hour had no agenda?",
    "prayerPrompt": "Lord, here is my hour; I want nothing from it but you.",
    "growthType": "flowers",
    "tags": [
      "rest",
      "presence",
      "quiet"
    ],
    "seasonTags": [
      "ordinary_time",
      "lent"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "thank-someone-in-your-family",
    "title": "Thank Someone in Your Family",
    "category": "family",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "Tell one family member, in person or by message, one specific thing you are thankful for about them.",
    "whyItMatters": "Gratitude kept inside blesses no one. Spoken plainly, it becomes a small gift that costs nothing and is rarely forgotten.",
    "scriptureReference": "Philippians 1:3",
    "scriptureText": "I thank my God whenever I remember you,",
    "reflectionPrompt": "What made you choose this person today?",
    "prayerPrompt": "Lord, thank you for the people you have placed in my life.",
    "growthType": "fruit",
    "tags": [
      "gratitude",
      "family",
      "encouragement"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "listen-without-fixing",
    "title": "Listen Without Fixing",
    "category": "family",
    "durationMinutes": 15,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Give a family member fifteen unhurried minutes today, listening without advice, correction, or fixing.",
    "whyItMatters": "Being truly heard is rare, and family often receives the least of our attention. Listening is a form of love that asks nothing in return.",
    "scriptureReference": "James 1:19",
    "scriptureText": "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger;",
    "reflectionPrompt": "What did you hear because you stayed quiet?",
    "prayerPrompt": "Lord, make me quick to listen and slow to speak.",
    "growthType": "leaves",
    "tags": [
      "listening",
      "family",
      "patience"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "pray-for-your-family-by-name",
    "title": "Pray for Your Family by Name",
    "category": "family",
    "durationMinutes": 10,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Sit somewhere quiet and pray for each member of your family by name, near or far, one at a time.",
    "whyItMatters": "Praying for someone by name turns a general love into a particular one. It is a way of carrying your family even when they are not near.",
    "scriptureReference": "Ephesians 1:16",
    "scriptureText": "don’t cease to give thanks for you, making mention of you in my prayers,",
    "reflectionPrompt": "Which name stayed with you after you finished?",
    "prayerPrompt": "Father, be near to each one I have named.",
    "growthType": "roots",
    "tags": [
      "prayer",
      "family",
      "intercession"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "do-one-chore-unasked",
    "title": "Do One Chore Unasked",
    "category": "family",
    "durationMinutes": 15,
    "difficulty": "gentle",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Quietly take care of one small task at home that usually belongs to someone else, without announcing it.",
    "whyItMatters": "Hidden service is love with no audience. Jesus washed feet; we can wash dishes.",
    "scriptureReference": "Galatians 5:13",
    "scriptureText": "For you, brothers, were called for freedom. Only don’t use your freedom for gain to the flesh, but through love be servants to one another.",
    "reflectionPrompt": "How did it feel to serve without being seen?",
    "prayerPrompt": "Lord, teach me to serve gladly in small things.",
    "growthType": "fruit",
    "tags": [
      "service",
      "home",
      "humility"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "ask-about-the-old-days",
    "title": "Ask About the Old Days",
    "category": "family",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Call or sit with an older family member today and ask them to tell you about a time they remember well.",
    "whyItMatters": "Every family carries stories that fade unless someone asks. Listening to our elders is an old and honored way of loving them.",
    "scriptureReference": "Deuteronomy 32:7",
    "scriptureText": "Remember the days of old. Consider the years of many generations. Ask your father, and he will show you; your elders, and they will tell you.",
    "reflectionPrompt": "What did you learn that you did not know before?",
    "prayerPrompt": "Lord, thank you for the lives that came before mine.",
    "growthType": "fruit",
    "tags": [
      "elders",
      "listening",
      "family"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive",
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "an-afternoon-of-gentle-words",
    "title": "An Afternoon of Gentle Words",
    "category": "family",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "low",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "Carry one quiet intention through your afternoon: to speak gently at home, and to simply begin again whenever you forget.",
    "whyItMatters": "Homes are built or worn down by ordinary words. Gentleness practiced for a single afternoon is a real gift to the people who live with us.",
    "scriptureReference": "Proverbs 15:1",
    "scriptureText": "A gentle answer turns away wrath, but a harsh word stirs up anger.",
    "reflectionPrompt": "When was it hardest to answer gently today?",
    "prayerPrompt": "Lord, let my words today be gentle ones.",
    "growthType": "leaves",
    "tags": [
      "gentleness",
      "speech",
      "home"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "one-hour-without-your-phone",
    "title": "One Hour Without Your Phone",
    "category": "discipline",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Set your phone in another room for one hour and let the quiet be what it is.",
    "whyItMatters": "Stepping away from the phone is a small fast, a way of making room. Even one hour of quiet can remind us that we are held.",
    "scriptureReference": "Psalm 46:10",
    "scriptureText": "“Be still, and know that I am God. I will be exalted among the nations. I will be exalted in the earth.”",
    "reflectionPrompt": "What rose up in the quiet once the noise was gone?",
    "prayerPrompt": "God, help me be still and know that you are here.",
    "growthType": "roots",
    "tags": [
      "silence",
      "rest",
      "phone"
    ],
    "seasonTags": [
      "ordinary_time",
      "lent"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [
      "discipline_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "a-psalm-before-your-phone",
    "title": "A Psalm Before Your Phone",
    "category": "discipline",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Before the next time you pick up your phone to scroll, read Psalm 23 slowly, just once.",
    "whyItMatters": "What we read first shapes how we see everything after. A psalm is a small lamp to carry into the rest of the day.",
    "scriptureReference": "Psalm 119:105",
    "scriptureText": "Your word is a lamp to my feet, and a light for my path.",
    "reflectionPrompt": "What line stayed with you?",
    "prayerPrompt": "Lord, let your word be the first voice I listen to.",
    "growthType": "branches",
    "tags": [
      "scripture",
      "psalms",
      "habits"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "one-hour-without-complaint",
    "title": "One Hour Without Complaint",
    "category": "discipline",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "For one hour, each time a complaint rises, let it pass and quietly name one true thing you are thankful for.",
    "whyItMatters": "Complaint narrows the heart; gratitude widens it. Christians have practiced this trade for centuries, one hour at a time.",
    "scriptureReference": "Philippians 2:14",
    "scriptureText": "Do all things without complaining and arguing,",
    "reflectionPrompt": "What did you notice about your own habits of speech?",
    "prayerPrompt": "Lord, turn my grumbling into gratitude.",
    "growthType": "flowers",
    "tags": [
      "gratitude",
      "speech",
      "self-control"
    ],
    "seasonTags": [
      "ordinary_time",
      "lent"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "discipline_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "five-minutes-of-stillness",
    "title": "Five Minutes of Stillness",
    "category": "discipline",
    "durationMinutes": 5,
    "difficulty": "gentle",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Sit still for five minutes today with nothing in your hands, and simply rest in God's presence.",
    "whyItMatters": "Stillness is not doing nothing. It is practicing trust, letting God hold the world for five minutes without our help.",
    "scriptureReference": "Psalm 62:1",
    "scriptureText": "My soul rests in God alone. My salvation is from him.",
    "reflectionPrompt": "What was it like to stop, even briefly?",
    "prayerPrompt": "God, quiet my heart the way a parent quiets a child.",
    "growthType": "roots",
    "tags": [
      "stillness",
      "silence",
      "rest"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "begin-what-you-have-put-off",
    "title": "Begin What You Have Put Off",
    "category": "discipline",
    "durationMinutes": 15,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Choose one small task you have been avoiding, at home or at work, and give it fifteen honest minutes today.",
    "whyItMatters": "Faithfulness is mostly made of small beginnings. Doing ordinary work with care is one way of offering it to God.",
    "scriptureReference": "Colossians 3:23",
    "scriptureText": "And whatever you do, work heartily, as for the Lord, and not for men,",
    "reflectionPrompt": "What made this task feel heavy, and what made it lighter once begun?",
    "prayerPrompt": "Lord, help me begin, and stay with me in the middle.",
    "growthType": "leaves",
    "tags": [
      "diligence",
      "work",
      "faithfulness"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "walk-without-headphones",
    "title": "Walk Without Headphones",
    "category": "discipline",
    "durationMinutes": 15,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Take a fifteen-minute walk outside without headphones, noticing what is alive and given around you.",
    "whyItMatters": "Attention is a discipline, and creation is always speaking. A quiet walk is one way to hear it.",
    "scriptureReference": "Psalm 19:1",
    "scriptureText": "The heavens declare the glory of God. The expanse shows his handiwork.",
    "reflectionPrompt": "What did you notice that you usually walk past?",
    "prayerPrompt": "God, open my eyes to what you have made.",
    "growthType": "sunlight",
    "tags": [
      "creation",
      "attention",
      "walking"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian",
      "exploring_friendly"
    ],
    "sensitivityTags": [],
    "isPremium": false
  }
];

export const questBySlug = new Map(seedQuests.map((q) => [q.slug, q]));
