// AUTO-GENERATED by scripts/build-quest-expansion.mjs — do not edit by hand.
// Canonical reviewed source: scripts/build-quest-expansion.mjs
// Scripture: exact local World English Bible text (public domain).

import type { QuestTemplate } from "@/lib/questos/types";

export const questExpansion: QuestTemplate[] = [
  {
    "slug": "pray-the-examen-before-sleep",
    "title": "Pray the Examen Before Sleep",
    "category": "prayer",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Before sleep, review the day with God: receive what was given, name where love grew thin, and entrust tomorrow without trying to solve it tonight.",
    "whyItMatters": "The examen trains honest attention without turning prayer into self-accusation. Grace gets the first and final word.",
    "scriptureReference": "Psalm 139:23-24",
    "scriptureText": "Search me, God, and know my heart. Try me, and know my thoughts. See if there is any wicked way in me, and lead me in the everlasting way.",
    "reflectionPrompt": "Where did you notice consolation, resistance, or an invitation for tomorrow?",
    "prayerPrompt": "Searching God, show me this day in the light of your mercy.",
    "growthType": "roots",
    "tags": [
      "examen",
      "discernment",
      "evening"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "intercede-for-your-community-map",
    "title": "Intercede With a Community Map",
    "category": "prayer",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Sketch the places that hold your community—schools, shelters, clinics, congregations, local government—and spend unhurried time praying for the people within each one.",
    "whyItMatters": "Intercession becomes less abstract when we remember the actual institutions and neighbors whose burdens shape shared life.",
    "scriptureReference": "1 Timothy 2:1-2",
    "scriptureText": "I exhort therefore, first of all, that petitions, prayers, intercessions, and givings of thanks be made for all men: for kings and all who are in high places, that we may lead a tranquil and quiet life in all godliness and reverence.",
    "reflectionPrompt": "Which place drew your attention, and what faithful action might accompany your prayer?",
    "prayerPrompt": "God of every street and household, give our community wisdom, protection, and peace.",
    "growthType": "branches",
    "tags": [
      "intercession",
      "community",
      "civic life"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "bring-a-lament-to-god",
    "title": "Bring a Lament to God",
    "category": "prayer",
    "durationMinutes": 30,
    "difficulty": "devoted",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Write a four-part lament: address God, name what is wrong without polishing it, ask clearly for help, and close with whatever trust you can honestly offer.",
    "whyItMatters": "Biblical lament refuses both denial and despair. It makes room for protest, petition, and relationship with God in the same prayer.",
    "scriptureReference": "Psalm 13:1-2",
    "scriptureText": "How long, Yahweh? Will you forget me forever? How long will you hide your face from me? How long shall I take counsel in my soul, having sorrow in my heart every day? How long shall my enemy triumph over me?",
    "reflectionPrompt": "What changed when you named the wound directly instead of explaining it away?",
    "prayerPrompt": "How long, O Lord? Meet me in what I cannot repair alone.",
    "growthType": "roots",
    "tags": [
      "lament",
      "honesty",
      "suffering"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "pray-scripture-over-one-person",
    "title": "Pray Scripture Over One Person",
    "category": "prayer",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Choose one person and slowly turn each phrase of Colossians 1:9-10 into a specific prayer for their wisdom, endurance, relationships, and work.",
    "whyItMatters": "Praying Scripture widens intercession beyond our immediate solutions and lets the shape of the text tutor our desires.",
    "scriptureReference": "Colossians 1:9-10",
    "scriptureText": "For this cause, we also, since the day we heard this, don’t cease praying and making requests for you, that you may be filled with the knowledge of his will in all spiritual wisdom and understanding, that you may walk worthily of the Lord, to please him in all respects, bearing fruit in every good work and increasing in the knowledge of God,",
    "reflectionPrompt": "Which petition felt most needed, and which challenged your assumptions about what they need?",
    "prayerPrompt": "God, fill them with wisdom that bears patient and generous fruit.",
    "growthType": "roots",
    "tags": [
      "intercession",
      "scripture prayer",
      "wisdom"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "walk-and-pray-your-neighborhood",
    "title": "Walk and Pray Your Neighborhood",
    "category": "prayer",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Walk a familiar route slowly. Pray without guessing private stories: bless the homes, workers, public spaces, and people you actually see, and notice one shared need.",
    "whyItMatters": "A prayer walk can grow responsible love when it attends to real neighbors without treating their lives as scenery or projects.",
    "scriptureReference": "Jeremiah 29:7",
    "scriptureText": "Seek the peace of the city where I have caused you to be carried away captive, and pray to Yahweh for it; for in its peace you will have peace.”",
    "reflectionPrompt": "What did you learn by paying attention, and where could prayer become respectful participation?",
    "prayerPrompt": "God of this place, teach me to seek my neighbors’ good with humility.",
    "growthType": "branches",
    "tags": [
      "prayer walk",
      "neighborhood",
      "attention"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "trace-mercy-through-a-gospel",
    "title": "Trace Mercy Through a Gospel",
    "category": "scripture",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Read one full chapter of Luke and mark every moment when Jesus notices, restores, confronts, or includes someone. Summarize the pattern in your own words.",
    "whyItMatters": "Following a theme through a whole chapter keeps one familiar line from carrying more weight than its narrative context.",
    "scriptureReference": "Luke 7:22-23",
    "scriptureText": "Jesus answered them, “Go and tell John the things which you have seen and heard: that the blind receive their sight, the lame walk, the lepers are cleansed, the deaf hear, the dead are raised up, and the poor have good news preached to them. Blessed is he who finds no occasion for stumbling in me.”",
    "reflectionPrompt": "What kind of mercy did you overlook before reading the whole scene?",
    "prayerPrompt": "Jesus, let the shape of your mercy correct and enlarge mine.",
    "growthType": "leaves",
    "tags": [
      "gospel",
      "context",
      "mercy"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "practice-lectio-divina",
    "title": "Practice Lectio Divina",
    "category": "scripture",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Read John 15:1-5 four times: listen for a word, notice your response, answer God honestly, then rest in silence without forcing an insight.",
    "whyItMatters": "This ancient rhythm slows interpretation enough for Scripture to become prayer while still honoring the words actually on the page.",
    "scriptureReference": "John 15:4-5",
    "scriptureText": "Remain in me, and I in you. As the branch can’t bear fruit by itself unless it remains in the vine, so neither can you, unless you remain in me. I am the vine. You are the branches. He who remains in me and I in him bears much fruit, for apart from me you can do nothing.",
    "reflectionPrompt": "Which word stayed, and how did your response change across the readings?",
    "prayerPrompt": "Living Christ, keep me near enough to receive and bear good fruit.",
    "growthType": "leaves",
    "tags": [
      "lectio divina",
      "meditation",
      "abiding"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "compare-two-resurrection-accounts",
    "title": "Compare Two Resurrection Accounts",
    "category": "scripture",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "indoor",
    "invitation": "Read Matthew 28 and John 20 side by side. List what each writer emphasizes, what questions remain, and what both accounts proclaim before consulting a study note.",
    "whyItMatters": "Comparison makes room for each Gospel’s witness instead of flattening distinct voices into a single imagined scene.",
    "scriptureReference": "John 20:30-31",
    "scriptureText": "Therefore Jesus did many other signs in the presence of his disciples, which are not written in this book; but these are written, that you may believe that Jesus is the Christ, the Son of God, and that believing you may have life in his name.",
    "reflectionPrompt": "What did one account help you see in the other?",
    "prayerPrompt": "Risen Jesus, meet me through the faithful witness of these texts.",
    "growthType": "leaves",
    "tags": [
      "resurrection",
      "study",
      "gospels"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "memorize-a-passage-in-context",
    "title": "Memorize a Passage in Context",
    "category": "scripture",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Read Philippians 2:1-11 in full, then memorize verses 3-5 across several short sessions. Return to the whole passage each time so the lines keep their context.",
    "whyItMatters": "Memory can make Scripture available under pressure; context keeps remembered words from becoming slogans detached from Christ’s way.",
    "scriptureReference": "Philippians 2:3-5",
    "scriptureText": "doing nothing through rivalry or through conceit, but in humility, each counting others better than himself; each of you not just looking to his own things, but each of you also to the things of others. Have this in your mind, which was also in Christ Jesus,",
    "reflectionPrompt": "Where does this passage confront ambition, fear, or the need to be noticed?",
    "prayerPrompt": "Christ Jesus, form your humility in my reflexes and relationships.",
    "growthType": "leaves",
    "tags": [
      "memory",
      "context",
      "humility"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "read-a-minor-prophet-whole",
    "title": "Read a Minor Prophet Whole",
    "category": "scripture",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Read the book of Habakkuk in one sitting. Track the movement from complaint to response to trust, noting where the prophet’s questions remain unresolved.",
    "whyItMatters": "A short biblical book read whole reveals an argument and emotional movement that isolated quotations cannot show.",
    "scriptureReference": "Habakkuk 3:17-18",
    "scriptureText": "For though the fig tree doesn’t flourish, nor fruit be in the vines; the labor of the olive fails, the fields yield no food; the flocks are cut off from the fold, and there is no herd in the stalls: yet I will rejoice in Yahweh. I will be joyful in the God of my salvation!",
    "reflectionPrompt": "How does Habakkuk’s final trust differ from pretending circumstances are fine?",
    "prayerPrompt": "Faithful God, hold my questions and teach me durable hope.",
    "growthType": "roots",
    "tags": [
      "prophets",
      "whole book",
      "lament"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "serve-a-local-need-with-consent",
    "title": "Serve a Local Need With Consent",
    "category": "service",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Give a half day to an established local organization. Ask what work is actually useful, follow the leaders closest to the need, and complete the unglamorous task you are given.",
    "whyItMatters": "Service becomes solidarity when it follows community wisdom rather than centering the helper’s assumptions or visibility.",
    "scriptureReference": "Philippians 2:3-4",
    "scriptureText": "doing nothing through rivalry or through conceit, but in humility, each counting others better than himself; each of you not just looking to his own things, but each of you also to the things of others.",
    "reflectionPrompt": "What did receiving direction teach you about dignity, power, and useful help?",
    "prayerPrompt": "Servant Christ, make me teachable, steady, and willing to do hidden work.",
    "growthType": "branches",
    "tags": [
      "volunteering",
      "solidarity",
      "local"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "make-a-practical-help-plan",
    "title": "Make a Practical Help Plan",
    "category": "service",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Ask someone carrying a real burden what kind of help would reduce it. Agree on one specific task, time, boundary, and follow-up instead of offering a vague promise.",
    "whyItMatters": "Concrete, consent-based help is easier to receive and less likely to create another decision for someone already overloaded.",
    "scriptureReference": "1 John 3:17-18",
    "scriptureText": "But whoever has the world’s goods and sees his brother in need, then closes his heart of compassion against him, how does God’s love remain in him? My little children, let’s not love in word only, or with the tongue only, but in deed and truth.",
    "reflectionPrompt": "Did your offer match the other person’s stated need, or your preferred way of helping?",
    "prayerPrompt": "God of practical love, make my care reliable and respectful.",
    "growthType": "branches",
    "tags": [
      "care",
      "reliability",
      "consent"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "offer-caregiver-respite",
    "title": "Offer Caregiver Respite",
    "category": "service",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "If it is welcome and within your competence, arrange a defined block of practical support for a caregiver—food, errands, sitting nearby, or another task they choose.",
    "whyItMatters": "Caregivers often carry invisible, sustained labor. Reliable respite honors limits and helps a community bear burdens together.",
    "scriptureReference": "Galatians 6:2",
    "scriptureText": "Bear one another’s burdens, and so fulfill the law of Christ.",
    "reflectionPrompt": "What structures would make this care sustainable rather than a one-time gesture?",
    "prayerPrompt": "Burden-bearing God, strengthen caregivers and teach us to share the load.",
    "growthType": "branches",
    "tags": [
      "caregiving",
      "respite",
      "community"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "repair-a-shared-space",
    "title": "Repair a Shared Space",
    "category": "service",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "high",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "Choose one neglected task in a shared space—cleaning, restocking, mending, organizing, or reporting a repair—and complete it without needing credit.",
    "whyItMatters": "Common life depends on maintenance that is easy to overlook. Hidden care can make a place safer and more welcoming for everyone.",
    "scriptureReference": "Colossians 3:23-24",
    "scriptureText": "And whatever you do, work heartily, as for the Lord, and not for men, knowing that from the Lord you will receive the reward of the inheritance; for you serve the Lord Christ.",
    "reflectionPrompt": "Whose often-unseen labor did this task help you notice?",
    "prayerPrompt": "God, receive this ordinary work and bless those who share this place.",
    "growthType": "branches",
    "tags": [
      "shared space",
      "hidden work",
      "stewardship"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "commit-to-a-month-of-service",
    "title": "Commit to a Month of Service",
    "category": "service",
    "durationMinutes": 480,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Research one trusted local effort, contact its coordinator, and make a realistic four-week commitment with dates you can honor. Use today to complete the first shift or orientation.",
    "whyItMatters": "Depth usually grows through accountable presence, not a burst of enthusiasm. A bounded commitment makes reliability possible.",
    "scriptureReference": "Hebrews 6:10",
    "scriptureText": "For God is not unrighteous, so as to forget your work and the labor of love which you showed toward his name, in that you served the saints, and still do serve them.",
    "reflectionPrompt": "What limit will help you keep this promise without resentment or burnout?",
    "prayerPrompt": "Steadfast God, make my yes honest and my service enduring.",
    "growthType": "branches",
    "tags": [
      "commitment",
      "volunteering",
      "faithfulness"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "prepare-for-a-repairing-conversation",
    "title": "Prepare for a Repairing Conversation",
    "category": "kindness",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Prepare for one safe conversation where harm or misunderstanding needs repair. Write what you can own, what you need to ask, and what boundary keeps the exchange truthful.",
    "whyItMatters": "Kindness is not avoidance. Careful preparation can hold honesty, responsibility, and another person’s dignity together.",
    "scriptureReference": "Ephesians 4:15",
    "scriptureText": "but speaking truth in love, we may grow up in all things into him who is the head, Christ,",
    "reflectionPrompt": "What can you take responsibility for without taking responsibility for everything?",
    "prayerPrompt": "God of truth and grace, govern my words and guard every person’s dignity.",
    "growthType": "flowers",
    "tags": [
      "repair",
      "truth",
      "communication"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "advocate-without-taking-over",
    "title": "Advocate Without Taking Over",
    "category": "kindness",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "With permission, use one piece of access or influence to support someone whose concern is being overlooked. Ask how they want support and keep their voice at the center.",
    "whyItMatters": "Advocacy can practice neighbor-love when it shares power instead of turning another person’s struggle into our own performance.",
    "scriptureReference": "Proverbs 31:8-9",
    "scriptureText": "Open your mouth for the mute, in the cause of all who are left desolate. Open your mouth, judge righteously, and serve justice to the poor and needy.”",
    "reflectionPrompt": "Did your action amplify the person’s agency, and what accountability is needed next?",
    "prayerPrompt": "God of justice, teach me to use influence with courage and humility.",
    "growthType": "branches",
    "tags": [
      "advocacy",
      "justice",
      "agency"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "welcome-someone-new-with-care",
    "title": "Welcome Someone New With Care",
    "category": "kindness",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "At a gathering, introduce yourself to someone who seems new, explain one useful detail, and offer connection without demanding conversation or personal disclosure.",
    "whyItMatters": "Thoughtful welcome lowers the invisible cost of entering an unfamiliar community while respecting a newcomer’s pace.",
    "scriptureReference": "Romans 15:7",
    "scriptureText": "Therefore accept one another, even as Christ also accepted you, to the glory of God.",
    "reflectionPrompt": "What made your welcome hospitable rather than intrusive?",
    "prayerPrompt": "Welcoming Christ, make room through me without making anyone perform belonging.",
    "growthType": "flowers",
    "tags": [
      "welcome",
      "hospitality",
      "belonging"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "honor-a-worker-by-name",
    "title": "Honor a Worker by Name",
    "category": "kindness",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Notice someone whose work is easy to treat as invisible. Learn and use their name if appropriate, thank them specifically, and make their work easier rather than interrupting it.",
    "whyItMatters": "Attention can resist the habit of reducing people to services. Specific gratitude recognizes dignity without requiring intimacy.",
    "scriptureReference": "Romans 12:10",
    "scriptureText": "In love of the brothers be tenderly affectionate to one another; in honor preferring one another;",
    "reflectionPrompt": "What systems or habits had made this person’s labor easy for you to overlook?",
    "prayerPrompt": "God, train my attention toward the dignity of every neighbor.",
    "growthType": "flowers",
    "tags": [
      "dignity",
      "work",
      "gratitude"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "practice-a-day-of-attentive-speech",
    "title": "Practice a Day of Attentive Speech",
    "category": "kindness",
    "durationMinutes": 480,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "For one day, pause before consequential words. Refuse gossip, ask one clarifying question before assuming, and repair quickly if your speech wounds or misrepresents.",
    "whyItMatters": "Speech shapes the emotional climate around us. A full day reveals patterns that a single kind sentence may leave untouched.",
    "scriptureReference": "James 1:19-20",
    "scriptureText": "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger; for the anger of man doesn’t produce the righteousness of God.",
    "reflectionPrompt": "When was silence wise, and when did love require clear speech?",
    "prayerPrompt": "God, set a guard over my mouth and courage in my truthful words.",
    "growthType": "flowers",
    "tags": [
      "speech",
      "listening",
      "integrity"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "separate-mercy-from-access",
    "title": "Separate Mercy From Access",
    "category": "forgiveness",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Journal two columns: what releasing vengeance to God could mean, and what wise boundaries still require. Do not contact anyone as part of this quest.",
    "whyItMatters": "Forgiveness is not denial, restored trust, or unlimited access. Distinguishing them protects truth and safety while making room for mercy.",
    "scriptureReference": "Romans 12:18-19",
    "scriptureText": "If it is possible, as much as it is up to you, be at peace with all men. Don’t seek revenge yourselves, beloved, but give place to God’s wrath. For it is written, “Vengeance belongs to me; I will repay, says the Lord.”",
    "reflectionPrompt": "Which boundary helps you refuse both revenge and renewed harm?",
    "prayerPrompt": "Just and merciful God, hold what I cannot safely carry or repair.",
    "growthType": "roots",
    "tags": [
      "boundaries",
      "mercy",
      "safety"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive",
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "lament-before-you-release",
    "title": "Lament Before You Release",
    "category": "forgiveness",
    "durationMinutes": 30,
    "difficulty": "devoted",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Name before God what was lost, what should have been different, and what consequence remains. Let lament come before any language of release.",
    "whyItMatters": "Rushing past grief can turn forgiveness into spiritual pressure. Lament honors the truth that mercy does not make harm unreal.",
    "scriptureReference": "Psalm 55:22",
    "scriptureText": "Cast your burden on Yahweh and he will sustain you. He will never allow the righteous to be moved.",
    "reflectionPrompt": "What needed acknowledgment before release could become honest?",
    "prayerPrompt": "God, receive my grief and keep me from carrying vengeance as my vocation.",
    "growthType": "roots",
    "tags": [
      "lament",
      "release",
      "truth"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive",
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "name-the-loss-beneath-anger",
    "title": "Name the Loss Beneath Anger",
    "category": "forgiveness",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Without excusing harm, ask what loss your anger is protecting—trust, safety, time, belonging, or hope. Name that loss in prayer or writing.",
    "whyItMatters": "Anger often guards something valuable. Naming the loss can clarify what healing and boundaries actually need.",
    "scriptureReference": "Ephesians 4:26-27",
    "scriptureText": "“Be angry, and don’t sin.” Don’t let the sun go down on your wrath, and don’t give place to the devil.",
    "reflectionPrompt": "What value or wound became clearer beneath the anger?",
    "prayerPrompt": "God, meet the loss beneath my anger and guide my next faithful step.",
    "growthType": "roots",
    "tags": [
      "anger",
      "grief",
      "discernment"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "practice-a-mercy-hour",
    "title": "Practice a Mercy Hour",
    "category": "forgiveness",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Set aside an hour to pray for freedom from resentment, write an unsent blessing that does not deny consequences, and choose one boundary or support you need.",
    "whyItMatters": "Forgiveness often unfolds through repeated, bounded practices rather than one decisive feeling.",
    "scriptureReference": "Luke 6:36-37",
    "scriptureText": "“Therefore be merciful, even as your Father is also merciful. Don’t judge, and you won’t be judged. Don’t condemn, and you won’t be condemned. Set free, and you will be set free.",
    "reflectionPrompt": "What can you release today, and what still needs time, protection, or wise counsel?",
    "prayerPrompt": "Merciful God, free me from vengeance without asking me to call harm good.",
    "growthType": "roots",
    "tags": [
      "mercy",
      "resentment",
      "boundaries"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "forgiveness_sensitive",
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "receive-forgiveness-with-repair",
    "title": "Receive Forgiveness With Repair",
    "category": "forgiveness",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "indoor",
    "invitation": "Name one wrong you have done. Confess it to God, identify repair that does not demand absolution from the harmed person, and take one accountable step if it is safe.",
    "whyItMatters": "Grace frees us to tell the truth and repair what we can; it does not erase consequences or make another person responsible for easing our guilt.",
    "scriptureReference": "1 John 1:8-9",
    "scriptureText": "If we say that we have no sin, we deceive ourselves, and the truth is not in us. If we confess our sins, he is faithful and righteous to forgive us the sins, and to cleanse us from all unrighteousness.",
    "reflectionPrompt": "What does repentance require beyond feeling sorry?",
    "prayerPrompt": "Merciful God, forgive me, make me truthful, and lead me into repair.",
    "growthType": "roots",
    "tags": [
      "confession",
      "repair",
      "grace"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "build-a-generous-budget-line",
    "title": "Build a Generous Budget Line",
    "category": "generosity",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Review one month of spending without shame. Choose a realistic recurring amount or resource to share, name its recipient, and protect your essential needs first.",
    "whyItMatters": "Planned generosity can outlast impulse and make giving both dependable and honest about financial limits.",
    "scriptureReference": "2 Corinthians 9:7-8",
    "scriptureText": "Let each man give according as he has determined in his heart, not grudgingly or under compulsion, for God loves a cheerful giver. And God is able to make all grace abound to you, that you, always having all sufficiency in everything, may abound to every good work.",
    "reflectionPrompt": "What amount is genuinely sustainable, and what value does it express?",
    "prayerPrompt": "Provider God, make me openhanded, prudent, and free from comparison.",
    "growthType": "fruit",
    "tags": [
      "budget",
      "giving",
      "sustainability"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "money_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "give-a-useful-possession-well",
    "title": "Give a Useful Possession Well",
    "category": "generosity",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "indoor",
    "invitation": "Choose something in good condition that another person or trusted organization has actually requested. Clean it, prepare it, and arrange a respectful handoff.",
    "whyItMatters": "Generosity considers the receiver’s needs and dignity; it is not a way to transfer clutter or create obligation.",
    "scriptureReference": "Luke 3:11",
    "scriptureText": "He answered them, “He who has two coats, let him give to him who has none. He who has food, let him do likewise.”",
    "reflectionPrompt": "Did the gift answer a real need, and what made the handoff respectful?",
    "prayerPrompt": "Generous God, help me share what is useful with joy and care.",
    "growthType": "fruit",
    "tags": [
      "possessions",
      "sharing",
      "dignity"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "share-a-skill-without-charge",
    "title": "Share a Skill Without Charge",
    "category": "generosity",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Offer a bounded block of a skill you genuinely have—repair, tutoring, cooking, translation, technology, or administration—to someone or a group that wants it.",
    "whyItMatters": "Time and competence are forms of wealth. A clear scope lets a generous offer remain useful and sustainable.",
    "scriptureReference": "1 Peter 4:10",
    "scriptureText": "As each has received a gift, employ it in serving one another, as good managers of the grace of God in its various forms.",
    "reflectionPrompt": "How did clear boundaries strengthen rather than diminish the gift?",
    "prayerPrompt": "God of varied gifts, let what I know become service rather than status.",
    "growthType": "fruit",
    "tags": [
      "skills",
      "time",
      "service"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "contribute-to-mutual-aid",
    "title": "Contribute to Mutual Aid",
    "category": "generosity",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Find a transparent, community-led mutual-aid request. Give money, supplies, signal-boosting, or labor within your means, following the stated need exactly.",
    "whyItMatters": "Mutual aid treats people as participants in shared survival rather than passive recipients of someone else’s generosity.",
    "scriptureReference": "Acts 4:34-35",
    "scriptureText": "For neither was there among them any who lacked, for as many as were owners of lands or houses sold them, and brought the proceeds of the things that were sold, and laid them at the apostles’ feet, and distribution was made to each, according as anyone had need.",
    "reflectionPrompt": "What did community leadership change about how you offered support?",
    "prayerPrompt": "God of enough, teach us to share so needs are met with dignity.",
    "growthType": "fruit",
    "tags": [
      "mutual aid",
      "community",
      "dignity"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "money_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "host-within-your-means",
    "title": "Host Within Your Means",
    "category": "generosity",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Invite one or more people into a simple meal or shared time. Ask about access and dietary needs, keep the offering affordable, and let presence matter more than presentation.",
    "whyItMatters": "Hospitality is the generous making of room. Simplicity protects it from becoming performance or financial strain.",
    "scriptureReference": "1 Peter 4:9",
    "scriptureText": "Be hospitable to one another without grumbling.",
    "reflectionPrompt": "What helped people participate as guests rather than audiences?",
    "prayerPrompt": "Welcoming God, make this space spacious in spirit and honest in its limits.",
    "growthType": "fruit",
    "tags": [
      "hospitality",
      "table",
      "welcome"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "money_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "write-a-sabbath-plan",
    "title": "Write a Sabbath Plan",
    "category": "discipline",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "indoor",
    "invitation": "Plan one realistic period of Sabbath: what you will stop, what restores delight and worship, who needs notice, and what preparation will keep rest from burdening someone else.",
    "whyItMatters": "Sabbath is more than collapsing after work. Deliberate preparation can make rest, worship, and justice more available.",
    "scriptureReference": "Mark 2:27-28",
    "scriptureText": "He said to them, “The Sabbath was made for man, not man for the Sabbath. Therefore the Son of Man is lord even of the Sabbath.”",
    "reflectionPrompt": "Whose labor makes your rest possible, and how will your plan honor them?",
    "prayerPrompt": "God of Sabbath, free me from proving my worth and teach me restorative rest.",
    "growthType": "roots",
    "tags": [
      "sabbath",
      "rest",
      "planning"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "create-a-digital-rule-of-life",
    "title": "Create a Digital Rule of Life",
    "category": "discipline",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Audit one week of digital habits. Write three specific boundaries for attention, sleep, and relationships, then configure one device setting that supports them.",
    "whyItMatters": "Technology is easier to steward through concrete defaults than through repeated acts of willpower and shame.",
    "scriptureReference": "1 Corinthians 6:12",
    "scriptureText": "“All things are lawful for me,” but not all things are expedient. “All things are lawful for me,” but I will not be brought under the power of anything.",
    "reflectionPrompt": "Which tool has quietly begun to master your attention, and what is a proportionate boundary?",
    "prayerPrompt": "God, order my attention toward what gives life and love.",
    "growthType": "leaves",
    "tags": [
      "technology",
      "attention",
      "rule of life"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "discipline_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "finish-a-promised-work",
    "title": "Finish a Promised Work",
    "category": "discipline",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "Choose one meaningful commitment you have delayed. Clarify the smallest honest definition of done, communicate if expectations changed, and give it a focused half day.",
    "whyItMatters": "Faithfulness includes truthful renegotiation as well as completion. Either is better than silent avoidance.",
    "scriptureReference": "Matthew 5:37",
    "scriptureText": "But let your ‘Yes’ be ‘Yes’ and your ‘No’ be ‘No.’ Whatever is more than these is of the evil one.",
    "reflectionPrompt": "Did integrity require finishing, apologizing, renegotiating, or all three?",
    "prayerPrompt": "Faithful God, make my commitments clear and my follow-through honest.",
    "growthType": "leaves",
    "tags": [
      "commitment",
      "work",
      "integrity"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "practice-hidden-faithfulness",
    "title": "Practice Hidden Faithfulness",
    "category": "discipline",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Do one necessary act of prayer, care, cleaning, preparation, or repair that no one is likely to notice. Resist hinting for recognition afterward.",
    "whyItMatters": "Hidden practice loosens the need for applause and makes room for faithfulness rooted in love rather than image.",
    "scriptureReference": "Matthew 6:3-4",
    "scriptureText": "But when you do merciful deeds, don’t let your left hand know what your right hand does, so that your merciful deeds may be in secret, then your Father who sees in secret will reward you openly.",
    "reflectionPrompt": "What did the desire to be noticed reveal, without judging yourself for having it?",
    "prayerPrompt": "God who sees in secret, make love enough reward for this work.",
    "growthType": "roots",
    "tags": [
      "hidden work",
      "humility",
      "faithfulness"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "keep-a-full-day-of-attention",
    "title": "Keep a Full Day of Attention",
    "category": "discipline",
    "durationMinutes": 480,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "Choose one day to single-task: silence nonessential alerts, make a short written plan, give people undivided attention, and pause between activities instead of filling every gap.",
    "whyItMatters": "Attention is a finite form of love. A full-day experiment reveals the systems that scatter it and the practices that restore it.",
    "scriptureReference": "Ephesians 5:15-16",
    "scriptureText": "Therefore watch carefully how you walk, not as unwise, but as wise, redeeming the time, because the days are evil.",
    "reflectionPrompt": "Where did focused presence change the quality of your work or relationships?",
    "prayerPrompt": "God of this present moment, gather my scattered attention into love.",
    "growthType": "leaves",
    "tags": [
      "attention",
      "presence",
      "single task"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "write-a-specific-gratitude-letter",
    "title": "Write a Specific Gratitude Letter",
    "category": "gratitude",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Write to someone whose ordinary faithfulness shaped you. Name a concrete moment, what it cost them, and how its fruit continues—without asking them to reassure or praise you back.",
    "whyItMatters": "Specific thanks honors another person more fully than general praise and helps memory resist taking love for granted.",
    "scriptureReference": "Philippians 1:3-5",
    "scriptureText": "I thank my God whenever I remember you, always in every request of mine on behalf of you all, making my requests with joy, for your partnership in furtherance of the Good News from the first day until now;",
    "reflectionPrompt": "What became visible when you traced the lasting fruit of their care?",
    "prayerPrompt": "God, thank you for the people through whom your care has reached me.",
    "growthType": "flowers",
    "tags": [
      "letter",
      "memory",
      "relationships"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "trace-grace-through-a-hard-year",
    "title": "Trace Grace Through a Hard Year",
    "category": "gratitude",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Make a timeline of a difficult season. Name both what hurt and the people, practices, provisions, or moments that helped you endure, without forcing the pain into a lesson.",
    "whyItMatters": "Gratitude can coexist with grief. Honest remembrance notices sustaining grace without calling suffering good.",
    "scriptureReference": "Lamentations 3:21-23",
    "scriptureText": "This I recall to my mind; therefore I have hope. It is because of Yahweh’s loving kindnesses that we are not consumed, because his compassion doesn’t fail. They are new every morning. Great is your faithfulness.",
    "reflectionPrompt": "What sustained you that you could not see clearly while surviving?",
    "prayerPrompt": "Faithful God, thank you for mercies that did not erase the sorrow but met me in it.",
    "growthType": "roots",
    "tags": [
      "grief",
      "memory",
      "grace"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "thank-three-generations",
    "title": "Thank Three Generations",
    "category": "gratitude",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Identify one elder, one peer, and one younger person whose gifts strengthen your community. Thank each specifically in a form that fits your relationship.",
    "whyItMatters": "Gratitude across generations resists the idea that wisdom, energy, or contribution belongs to only one age group.",
    "scriptureReference": "Psalm 145:4",
    "scriptureText": "One generation will commend your works to another, and will declare your mighty acts.",
    "reflectionPrompt": "What distinct gift did each generation reveal?",
    "prayerPrompt": "God of every generation, teach us to receive and honor one another’s gifts.",
    "growthType": "flowers",
    "tags": [
      "generations",
      "community",
      "honor"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "practice-gratitude-without-denial",
    "title": "Practice Gratitude Without Denial",
    "category": "gratitude",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Complete two honest sentences: “Today is hard because…” and “Today also contains…” Repeat until neither sentence has to cancel the other.",
    "whyItMatters": "Mature gratitude does not suppress sorrow. It expands attention enough to hold pain and gift together.",
    "scriptureReference": "2 Corinthians 6:10",
    "scriptureText": "as sorrowful, yet always rejoicing; as poor, yet making many rich; as having nothing, and yet possessing all things.",
    "reflectionPrompt": "What truth became possible when you stopped making gratitude compete with grief?",
    "prayerPrompt": "God, hold what hurts and help me receive what is still given.",
    "growthType": "roots",
    "tags": [
      "honesty",
      "sorrow",
      "gift"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "lead-table-thanks-with-stories",
    "title": "Lead Table Thanks With Stories",
    "category": "gratitude",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Invite the people at a meal or gathering to name one gift from the week and the story behind it. Make passing welcome and do not correct anyone’s answer.",
    "whyItMatters": "Shared gratitude deepens when it makes room for particular stories and does not demand a cheerful performance.",
    "scriptureReference": "Psalm 107:1-2",
    "scriptureText": "Give thanks to Yahweh, for he is good, for his loving kindness endures forever. Let the redeemed by Yahweh say so, whom he has redeemed from the hand of the adversary,",
    "reflectionPrompt": "What did you learn about another person through the story behind their thanks?",
    "prayerPrompt": "Giver of daily bread, receive our varied stories and deepen our care.",
    "growthType": "flowers",
    "tags": [
      "table",
      "stories",
      "community"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "practice-centering-prayer",
    "title": "Practice Centering Prayer",
    "category": "silence",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Choose a simple sacred word as consent to God’s presence. Sit quietly; whenever thoughts carry you away, return gently without evaluating the session.",
    "whyItMatters": "Centering prayer practices consent and return. Its fruit is not a blank mind but a less defensive availability to God.",
    "scriptureReference": "Psalm 62:1-2",
    "scriptureText": "My soul rests in God alone. My salvation is from him. He alone is my rock, my salvation, and my fortress. I will never be greatly shaken.",
    "reflectionPrompt": "What did returning gently teach you about distraction and grace?",
    "prayerPrompt": "God, I consent to your presence and return without fear.",
    "growthType": "roots",
    "tags": [
      "centering prayer",
      "silence",
      "presence"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "take-a-silent-scripture-retreat",
    "title": "Take a Silent Scripture Retreat",
    "category": "silence",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Set aside an uninterrupted hour with a short Gospel passage, a notebook, and silence. Read slowly, walk or sit, and leave the final ten minutes without input.",
    "whyItMatters": "A bounded retreat creates enough space for attention to settle without requiring special travel or spiritual achievement.",
    "scriptureReference": "Mark 6:31",
    "scriptureText": "He said to them, “You come apart into a deserted place, and rest awhile.” For there were many coming and going, and they had no leisure so much as to eat.",
    "reflectionPrompt": "What surfaced only after the first layer of noise passed?",
    "prayerPrompt": "Jesus, lead me to a quiet place and meet me without hurry.",
    "growthType": "roots",
    "tags": [
      "retreat",
      "scripture",
      "quiet"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "keep-a-half-day-digital-silence",
    "title": "Keep a Half-Day Digital Silence",
    "category": "silence",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Choose four hours without optional screens or audio. Tell anyone who relies on you, keep emergency access available, and use the space for rest, prayer, reading, or unhurried work.",
    "whyItMatters": "Digital silence reveals which inputs restore us and which keep the nervous system from ever becoming quiet.",
    "scriptureReference": "Isaiah 30:15",
    "scriptureText": "For thus said the Lord Yahweh, the Holy One of Israel, “You will be saved in returning and rest. Your strength will be in quietness and in confidence.” You refused,",
    "reflectionPrompt": "What urge arrived first when input stopped, and what arrived later?",
    "prayerPrompt": "God of quiet strength, meet me beneath the stream of noise.",
    "growthType": "roots",
    "tags": [
      "digital silence",
      "rest",
      "attention"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "discipline_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "listen-to-the-neighborhood",
    "title": "Listen to the Neighborhood",
    "category": "silence",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Sit or walk outdoors without headphones. For thirty minutes, receive sound without naming it good or bad; notice human life, creation, machinery, distance, and silence between sounds.",
    "whyItMatters": "Contemplative listening turns a familiar place from background into a community of lives and limits worthy of attention.",
    "scriptureReference": "1 Kings 19:11-12",
    "scriptureText": "He said, “Go out, and stand on the mountain before Yahweh.” Behold, Yahweh passed by, and a great and strong wind tore the mountains, and broke in pieces the rocks before Yahweh; but Yahweh was not in the wind. After the wind there was an earthquake; but Yahweh was not in the earthquake. After the earthquake a fire passed; but Yahweh was not in the fire. After the fire, there was a still small voice.",
    "reflectionPrompt": "Which sound changed how you understood the place you inhabit?",
    "prayerPrompt": "God, quiet my judgments long enough to hear what is here.",
    "growthType": "sunlight",
    "tags": [
      "listening",
      "neighborhood",
      "creation"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "hold-silence-with-unanswered-questions",
    "title": "Hold Silence With an Unanswered Question",
    "category": "silence",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Bring one unresolved question into an hour of silence. Write it once, resist manufacturing an answer, and close by naming what you know, what you do not know, and whom you trust.",
    "whyItMatters": "Silence can form patience with mystery and keep discernment from becoming a demand for instant certainty.",
    "scriptureReference": "Habakkuk 2:1",
    "scriptureText": "I will stand at my watch, and set myself on the ramparts, and will look out to see what he will say to me, and what I will answer concerning my complaint.",
    "reflectionPrompt": "What changed when you stopped trying to force clarity?",
    "prayerPrompt": "God of mystery, keep me faithful while the answer is still unfinished.",
    "growthType": "roots",
    "tags": [
      "discernment",
      "mystery",
      "waiting"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "create-a-home-liturgy",
    "title": "Create a Home Liturgy",
    "category": "worship",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "indoor",
    "invitation": "Shape a simple service for your household or yourself: gathering words, one Psalm, confession, Scripture, intercession, gratitude, and a blessing. Keep it brief enough to repeat.",
    "whyItMatters": "A small liturgy gives ordinary space a shared rhythm of truth, prayer, and response without trying to replace gathered church.",
    "scriptureReference": "Colossians 3:16",
    "scriptureText": "Let the word of Christ dwell in you richly; in all wisdom teaching and admonishing one another with psalms, hymns, and spiritual songs, singing with grace in your heart to the Lord.",
    "reflectionPrompt": "Which movement helped worship become more than a mood?",
    "prayerPrompt": "God, inhabit these ordinary rooms and order our life toward praise.",
    "growthType": "sunlight",
    "tags": [
      "liturgy",
      "home",
      "rhythm"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "keep-three-hours-of-prayer",
    "title": "Keep Three Hours of Prayer",
    "category": "worship",
    "durationMinutes": 480,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "At morning, midday, and evening, pause for a Psalm, the Lord’s Prayer, and intercession. Set the times now and return even if one pause is imperfect.",
    "whyItMatters": "Fixed-hour prayer lets worship interrupt the day instead of waiting for attention to become convenient.",
    "scriptureReference": "Psalm 55:17",
    "scriptureText": "Evening, morning, and at noon, I will cry out in distress. He will hear my voice.",
    "reflectionPrompt": "How did returning at different hours change your awareness of the day?",
    "prayerPrompt": "God of morning, noon, and night, gather every hour into your care.",
    "growthType": "sunlight",
    "tags": [
      "daily office",
      "hours",
      "rhythm"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "study-and-sing-one-hymn",
    "title": "Study and Sing One Hymn",
    "category": "worship",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Choose a hymn or worship song rooted in Scripture. Read the lyrics, identify its claims about God, compare one claim with its biblical source, then sing or speak it attentively.",
    "whyItMatters": "Examining what we sing joins affection with discernment and helps worship form truthful imagination.",
    "scriptureReference": "Ephesians 5:19-20",
    "scriptureText": "speaking to one another in psalms, hymns, and spiritual songs; singing and making melody in your heart to the Lord; giving thanks always concerning all things in the name of our Lord Jesus Christ, to God, even the Father;",
    "reflectionPrompt": "Which lyric became richer, harder, or more honest after close attention?",
    "prayerPrompt": "God, tune my praise to truth as well as feeling.",
    "growthType": "sunlight",
    "tags": [
      "hymn",
      "theology",
      "song"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "make-an-art-offering",
    "title": "Make an Art Offering",
    "category": "worship",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "high",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Create a poem, sketch, melody, photograph, movement, or handmade object in response to one Psalm. Let it be an offering rather than a product you must post or perfect.",
    "whyItMatters": "Creative worship answers God with the embodied gifts and materials already at hand.",
    "scriptureReference": "Psalm 96:1-2",
    "scriptureText": "Sing to Yahweh a new song! Sing to Yahweh, all the earth. Sing to Yahweh! Bless his name! Proclaim his salvation from day to day!",
    "reflectionPrompt": "What did the act of making let you say that ordinary speech did not?",
    "prayerPrompt": "Creator God, receive this imperfect work as attentive praise.",
    "growthType": "flowers",
    "tags": [
      "art",
      "creativity",
      "psalm"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "take-a-resurrection-praise-walk",
    "title": "Take a Resurrection Praise Walk",
    "category": "worship",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "outdoor",
    "invitation": "Walk outdoors and pray through signs of life, decay, labor, and renewal. Read 1 Corinthians 15:54-58 midway and end by naming work that is not in vain.",
    "whyItMatters": "Resurrection hope does not ignore mortality; it declares that death and faithful labor do not have the final word.",
    "scriptureReference": "1 Corinthians 15:57-58",
    "scriptureText": "But thanks be to God, who gives us the victory through our Lord Jesus Christ. Therefore, my beloved brothers, be steadfast, immovable, always abounding in the Lord’s work, because you know that your labor is not in vain in the Lord.",
    "reflectionPrompt": "Where did resurrection hope meet the actual world rather than an ideal one?",
    "prayerPrompt": "Risen Christ, make me steadfast, hopeful, and alive in your work.",
    "growthType": "sunlight",
    "tags": [
      "resurrection",
      "creation",
      "praise"
    ],
    "seasonTags": [
      "easter"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "record-a-family-faith-story",
    "title": "Record a Family Faith Story",
    "category": "family",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Invite a relative or chosen-family elder to tell one story about faith, doubt, survival, or change. Ask permission before recording or sharing, and listen without correcting their memory.",
    "whyItMatters": "Family stories carry both wisdom and complexity. Consent and curiosity help receive them without turning them into polished legends.",
    "scriptureReference": "Deuteronomy 6:20-21",
    "scriptureText": "When your son asks you in time to come, saying, “What do the testimonies, the statutes, and the ordinances, which Yahweh our God has commanded you mean?” then you shall tell your son, “We were Pharaoh’s slaves in Egypt. Yahweh brought us out of Egypt with a mighty hand;",
    "reflectionPrompt": "What did the story reveal about both faith and the world that shaped it?",
    "prayerPrompt": "God of our complicated histories, help us receive truth with gratitude and care.",
    "growthType": "branches",
    "tags": [
      "story",
      "generations",
      "listening"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "offer-a-household-blessing",
    "title": "Offer a Household Blessing",
    "category": "family",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Write a brief blessing for the people who share your home or form your chosen family. Speak or send it only in a way that respects each person’s beliefs and comfort.",
    "whyItMatters": "A blessing names belovedness and hope without controlling another person’s spiritual response.",
    "scriptureReference": "Numbers 6:24-26",
    "scriptureText": "‘Yahweh bless you, and keep you. Yahweh make his face to shine on you, and be gracious to you. Yahweh lift up his face toward you, and give you peace.’",
    "reflectionPrompt": "What good did you most want to name over this household?",
    "prayerPrompt": "God, keep this household in peace, courage, truth, and generous love.",
    "growthType": "branches",
    "tags": [
      "blessing",
      "household",
      "chosen family"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "hold-a-family-boundaries-conversation",
    "title": "Hold a Family Boundaries Conversation",
    "category": "family",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "If it is safe, discuss one recurring household strain using a clear request, a listening turn for each person, and a boundary that no one must violate to keep the peace.",
    "whyItMatters": "Healthy family love needs truth and limits. Peace built on coercion or silence is not the wholeness Scripture describes.",
    "scriptureReference": "Romans 12:18",
    "scriptureText": "If it is possible, as much as it is up to you, be at peace with all men.",
    "reflectionPrompt": "What belongs to your responsibility, and what does not?",
    "prayerPrompt": "God of peace, make us truthful, safe, and willing to honor wise limits.",
    "growthType": "branches",
    "tags": [
      "boundaries",
      "communication",
      "peace"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "plan-a-household-service-day",
    "title": "Plan a Household Service Day",
    "category": "family",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Choose a community-defined need your household can serve together. Give each person a meaningful role, prepare for access needs, and end by reflecting on what you learned—not how impressive you were.",
    "whyItMatters": "Shared service can form a household when it centers neighbors’ stated needs and makes participation possible across ages and abilities.",
    "scriptureReference": "Joshua 24:15",
    "scriptureText": "If it seems evil to you to serve Yahweh, choose today whom you will serve; whether the gods which your fathers served that were beyond the River, or the gods of the Amorites, in whose land you dwell; but as for me and my house, we will serve Yahweh.”",
    "reflectionPrompt": "How did each person contribute, and what should your household learn before serving again?",
    "prayerPrompt": "Serving God, shape this household into a reliable neighbor.",
    "growthType": "branches",
    "tags": [
      "household",
      "service",
      "participation"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "attend-a-community-meeting",
    "title": "Attend a Community Meeting",
    "category": "community",
    "durationMinutes": 240,
    "difficulty": "devoted",
    "energyLevel": "high",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Attend a public, school, neighborhood, or congregational meeting about an issue that affects shared life. Listen before speaking, note who is missing, and identify one responsible follow-up.",
    "whyItMatters": "Seeking a community’s welfare requires learning how decisions are made and whose experience is heard.",
    "scriptureReference": "Jeremiah 29:7",
    "scriptureText": "Seek the peace of the city where I have caused you to be carried away captive, and pray to Yahweh for it; for in its peace you will have peace.”",
    "reflectionPrompt": "Whose knowledge shaped the meeting, and whose perspective still needs room?",
    "prayerPrompt": "God of the common good, make me patient in listening and faithful in participation.",
    "growthType": "branches",
    "tags": [
      "civic life",
      "listening",
      "common good"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "map-your-communitys-assets",
    "title": "Map Your Community’s Assets",
    "category": "community",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "either",
    "invitation": "List not only needs but also the people, associations, places, skills, and traditions already strengthening your community. Add one connection that could help two assets cooperate.",
    "whyItMatters": "Asset mapping resists defining communities only by deficits and honors wisdom that already lives close to the work.",
    "scriptureReference": "1 Corinthians 12:4-7",
    "scriptureText": "Now there are various kinds of gifts, but the same Spirit. There are various kinds of service, and the same Lord. There are various kinds of workings, but the same God, who works all things in all. But to each one is given the manifestation of the Spirit for the profit of all.",
    "reflectionPrompt": "Which strength had you overlooked because it was ordinary or informal?",
    "prayerPrompt": "God of many gifts, help us recognize and connect what you have already given.",
    "growthType": "branches",
    "tags": [
      "assets",
      "community",
      "collaboration"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "practice-community-conflict-with-boundaries",
    "title": "Practice Community Conflict With Boundaries",
    "category": "community",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "For one safe, current disagreement, write the shared concern, the point of conflict, the voices with authority, and a next conversation with ground rules. Seek mediation when power or safety requires it.",
    "whyItMatters": "Faithful conflict neither avoids truth nor treats winning as reconciliation. Structure can protect dignity and accountability.",
    "scriptureReference": "James 3:17-18",
    "scriptureText": "But the wisdom that is from above is first pure, then peaceful, gentle, reasonable, full of mercy and good fruits, without partiality, and without hypocrisy. Now the fruit of righteousness is sown in peace by those who make peace.",
    "reflectionPrompt": "What would a just process require, even if agreement remains incomplete?",
    "prayerPrompt": "God of wisdom, make our peacemaking pure, open to reason, and full of mercy.",
    "growthType": "branches",
    "tags": [
      "conflict",
      "mediation",
      "boundaries"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "relationship_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "support-a-weary-community-leader",
    "title": "Support a Weary Community Leader",
    "category": "community",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Ask a trusted community leader what small task would genuinely reduce their load this week. Accept the answer, including no, and do not use the offer to gain access or influence.",
    "whyItMatters": "Leaders need care that does not create new emotional labor or hidden obligation. Specific, bounded help can sustain shared work.",
    "scriptureReference": "1 Thessalonians 5:12-13",
    "scriptureText": "But we beg you, brothers, to know those who labor among you, and are over you in the Lord, and admonish you, and to respect and honor them in love for their work’s sake. Be at peace among yourselves.",
    "reflectionPrompt": "How did you keep support from becoming another demand?",
    "prayerPrompt": "God, sustain those who carry responsibility and make our help clean-hearted.",
    "growthType": "branches",
    "tags": [
      "leadership",
      "support",
      "boundaries"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "draft-a-rule-of-life",
    "title": "Draft a Rule of Life",
    "category": "reflection",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Draft a one-page rule for prayer, body, work, relationships, rest, money, and service. Choose practices small enough for your real season, plus a date to review them.",
    "whyItMatters": "A rule of life is a trellis, not a scorecard. It helps values become repeatable rhythms while leaving room for grace and revision.",
    "scriptureReference": "John 15:4-5",
    "scriptureText": "Remain in me, and I in you. As the branch can’t bear fruit by itself unless it remains in the vine, so neither can you, unless you remain in me. I am the vine. You are the branches. He who remains in me and I in him bears much fruit, for apart from me you can do nothing.",
    "reflectionPrompt": "Which rhythm supports life now, and which ideal belongs to a different season?",
    "prayerPrompt": "God, give my days a shape that makes room for love.",
    "growthType": "roots",
    "tags": [
      "rule of life",
      "rhythm",
      "discernment"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "discern-a-decision-with-counsel",
    "title": "Discern a Decision With Counsel",
    "category": "reflection",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "either",
    "indoorOrOutdoor": "indoor",
    "invitation": "For one meaningful decision, list facts, desires, fears, obligations, affected people, and wise counselors. Name what information is still missing before calling a preference God’s answer.",
    "whyItMatters": "Discernment integrates prayer, reason, community, and consequences rather than using spiritual language to escape uncertainty.",
    "scriptureReference": "Proverbs 15:22",
    "scriptureText": "Where there is no counsel, plans fail; but in a multitude of counselors they are established.",
    "reflectionPrompt": "Which desire needs honoring, and which assumption needs testing?",
    "prayerPrompt": "God of wisdom, free me from haste and make me receptive to truth.",
    "growthType": "roots",
    "tags": [
      "discernment",
      "decision",
      "counsel"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "make-a-season-of-life-timeline",
    "title": "Make a Season-of-Life Timeline",
    "category": "reflection",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Map the last twelve months with changes, losses, joys, responsibilities, and moments of grace. Circle what still asks for grief, gratitude, repair, or rest.",
    "whyItMatters": "Reflection helps scattered events become a season we can name, receive, and respond to honestly.",
    "scriptureReference": "Ecclesiastes 3:1",
    "scriptureText": "For everything there is a season, and a time for every purpose under heaven:",
    "reflectionPrompt": "What season are you actually in—not the one you think you should be in?",
    "prayerPrompt": "God of every season, teach me the faithful work of this one.",
    "growthType": "roots",
    "tags": [
      "timeline",
      "season",
      "self knowledge"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "turn-confession-into-a-next-step",
    "title": "Turn Confession Into a Next Step",
    "category": "reflection",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "Name one repeated pattern without contempt. Identify its trigger, its cost, a truthful confession, one repair, and one environmental change that supports a different response.",
    "whyItMatters": "Confession opens toward grace and transformation; shame only circles the self. A concrete next step lets truth bear fruit.",
    "scriptureReference": "Psalm 51:10-12",
    "scriptureText": "Create in me a clean heart, O God. Renew a right spirit within me. Don’t throw me from your presence, and don’t take your Holy Spirit from me. Restore to me the joy of your salvation. Uphold me with a willing spirit.",
    "reflectionPrompt": "What support or changed condition could make repentance more than intention?",
    "prayerPrompt": "Creating God, renew a steadfast spirit in me and lead me into repair.",
    "growthType": "roots",
    "tags": [
      "confession",
      "habit",
      "repair"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "practice-long-listening",
    "title": "Practice Long Listening",
    "category": "patience",
    "durationMinutes": 30,
    "difficulty": "steady",
    "energyLevel": "low",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "indoor",
    "invitation": "Invite someone to speak about something that matters to them. Ask open questions, leave pauses unfilled, and summarize what you heard before offering advice—if advice is wanted.",
    "whyItMatters": "Patient listening gives another person room to remain the author of their own experience.",
    "scriptureReference": "James 1:19",
    "scriptureText": "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger;",
    "reflectionPrompt": "What did you hear only because you did not rush to solve?",
    "prayerPrompt": "Listening God, slow my answers and deepen my attention.",
    "growthType": "branches",
    "tags": [
      "listening",
      "presence",
      "relationships"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "wait-with-someone",
    "title": "Wait With Someone",
    "category": "patience",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "low",
    "soloOrSocial": "social",
    "indoorOrOutdoor": "either",
    "invitation": "Offer company to someone waiting through an appointment, transition, grief, decision, or uncertain news. Let them choose conversation, practical help, distraction, or quiet.",
    "whyItMatters": "Presence cannot control an outcome, but it can keep uncertainty from becoming isolation.",
    "scriptureReference": "Romans 12:15",
    "scriptureText": "Rejoice with those who rejoice. Weep with those who weep.",
    "reflectionPrompt": "What did companionship make possible without fixing the situation?",
    "prayerPrompt": "Patient Christ, help me stay present without taking over.",
    "growthType": "branches",
    "tags": [
      "waiting",
      "companionship",
      "presence"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [
      "grief_sensitive"
    ],
    "isPremium": false
  },
  {
    "slug": "do-unfinished-work-slowly",
    "title": "Do Unfinished Work Slowly",
    "category": "patience",
    "durationMinutes": 60,
    "difficulty": "steady",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "either",
    "invitation": "Choose work that resists quick completion—a repair, skill, garden task, careful reading, or long-form planning—and give it an hour without measuring success by finishing.",
    "whyItMatters": "Patient labor retrains the demand for immediate results and honors growth that cannot be hurried.",
    "scriptureReference": "James 5:7-8",
    "scriptureText": "Be patient therefore, brothers, until the coming of the Lord. Behold, the farmer waits for the precious fruit of the earth, being patient over it, until it receives the early and late rain. You also be patient. Establish your hearts, for the coming of the Lord is at hand.",
    "reflectionPrompt": "What became possible when progress mattered more than completion?",
    "prayerPrompt": "God of slow growth, steady my hands and enlarge my time horizon.",
    "growthType": "leaves",
    "tags": [
      "slow work",
      "craft",
      "perseverance"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  },
  {
    "slug": "write-a-patient-hope-plan",
    "title": "Write a Patient Hope Plan",
    "category": "patience",
    "durationMinutes": 60,
    "difficulty": "devoted",
    "energyLevel": "medium",
    "soloOrSocial": "solo",
    "indoorOrOutdoor": "indoor",
    "invitation": "For one hope that may take months, write what is within your control, what is not, what support you need, the next review date, and how you will live meaningfully while you wait.",
    "whyItMatters": "Patient hope is active without pretending to command timing. It pairs faithful action with release of the outcome.",
    "scriptureReference": "Romans 8:24-25",
    "scriptureText": "For we were saved in hope, but hope that is seen is not hope. For who hopes for that which he sees? But if we hope for that which we don’t see, we wait for it with patience.",
    "reflectionPrompt": "What can you practice now without treating the future as a verdict on your worth?",
    "prayerPrompt": "God of hope, make me faithful in action and free in what I release.",
    "growthType": "roots",
    "tags": [
      "hope",
      "planning",
      "waiting"
    ],
    "seasonTags": [
      "ordinary_time"
    ],
    "traditionTags": [
      "broadly_christian"
    ],
    "sensitivityTags": [],
    "isPremium": false
  }
];
