// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
// Reflection prompts
// Content verified by the biblequest-seed-content workflow (safety + tone + theology lenses).
// Scripture text: World English Bible (public domain).

import type { ReflectionPromptSeed } from "@/lib/questos/types";

export const reflectionPrompts: ReflectionPromptSeed[] = [
  {
    "id": "r01",
    "text": "What is one thing from today's quest you'd like to carry with you?",
    "context": "after_quest"
  },
  {
    "id": "r02",
    "text": "Was there a moment in this quest that slowed you down, in a good way?",
    "context": "after_quest"
  },
  {
    "id": "r03",
    "text": "What surprised you as you walked through this step?",
    "context": "after_quest"
  },
  {
    "id": "r04",
    "text": "If you shared one thing from today's quest with a friend, what would it be?",
    "context": "after_quest"
  },
  {
    "id": "r05",
    "text": "Which word or phrase stayed with you after the reading ended?",
    "context": "after_scripture"
  },
  {
    "id": "r06",
    "text": "Where does this passage meet something you're living right now?",
    "context": "after_scripture"
  },
  {
    "id": "r07",
    "text": "If you could sit with the writer of these verses, what would you ask?",
    "context": "after_scripture"
  },
  {
    "id": "r08",
    "text": "What part of this passage would you like to return to tomorrow?",
    "context": "after_scripture"
  },
  {
    "id": "r09",
    "text": "What did you notice in the quiet, before or after the words?",
    "context": "after_prayer"
  },
  {
    "id": "r10",
    "text": "Is there something you didn't say in prayer that you'd like to name here?",
    "context": "after_prayer"
  },
  {
    "id": "r11",
    "text": "How do you feel now, compared to when you began to pray?",
    "context": "after_prayer"
  },
  {
    "id": "r12",
    "text": "What are you leaving in God's hands as you go?",
    "context": "after_prayer"
  },
  {
    "id": "r13",
    "text": "What would it look like to move through today a little more gently?",
    "context": "morning"
  },
  {
    "id": "r14",
    "text": "Who might need your patience today?",
    "context": "morning"
  },
  {
    "id": "r15",
    "text": "What small kindness could you carry into the hours ahead?",
    "context": "morning"
  },
  {
    "id": "r16",
    "text": "As the day begins, what do you hope to remember by evening?",
    "context": "morning"
  },
  {
    "id": "r17",
    "text": "Looking back, where did today feel most alive?",
    "context": "evening"
  },
  {
    "id": "r18",
    "text": "What moment from today deserves a second look before you rest?",
    "context": "evening"
  },
  {
    "id": "r19",
    "text": "What small mercy almost went unnoticed today?",
    "context": "evening"
  },
  {
    "id": "r20",
    "text": "What can you set down before you sleep?",
    "context": "evening"
  },
  {
    "id": "r21",
    "text": "What is something ordinary you would miss if it were gone?",
    "context": "gratitude"
  },
  {
    "id": "r22",
    "text": "Who has been kind to you lately, in ways big or small?",
    "context": "gratitude"
  },
  {
    "id": "r23",
    "text": "What good thing came to you today that you didn't ask for?",
    "context": "gratitude"
  },
  {
    "id": "r24",
    "text": "When did you last feel simply glad — and what was happening?",
    "context": "gratitude"
  },
  {
    "id": "r25",
    "text": "What feels heavy to carry right now?",
    "context": "difficulty"
  },
  {
    "id": "r26",
    "text": "If your worry could speak plainly, what would it say?",
    "context": "difficulty"
  },
  {
    "id": "r27",
    "text": "What kind of help would actually help today?",
    "context": "difficulty"
  },
  {
    "id": "r28",
    "text": "Where do you need mercy right now — from God, from others, or from yourself?",
    "context": "difficulty"
  },
  {
    "id": "r29",
    "text": "What are you noticing about yourself in this season?",
    "context": "general"
  },
  {
    "id": "r30",
    "text": "What question have you been living with lately?",
    "context": "general"
  },
  {
    "id": "r31",
    "text": "What would real rest look like for you this week?",
    "context": "general"
  },
  {
    "id": "r32",
    "text": "What would you like to begin again?",
    "context": "general"
  }
];
