-- MOVED — do not edit here.
--
-- BibleQuest's Row Level Security is now a numbered migration:
--     supabase/migrations/0002_rls_policies.sql
--
-- This keeps a single source of truth so `supabase db reset` reproduces the
-- deployed RLS state. This file is retained only so old references don't 404;
-- it is intentionally empty of runnable DDL. Delete it once nothing points here.
