-- MOVED — do not run policy DDL from this compatibility file.
--
-- BibleQuest's current Row Level Security reconciliation is the forward-only
-- numbered migration:
--     supabase/migrations/0008_reassert_rls_and_purge.sql
--
-- Earlier numbered migrations are preserved because they may already be in a
-- database's migration history. This file remains only so old references do
-- not 404; it is intentionally empty of runnable DDL.
