"use client";

import {
  LEGACY_ARCADE_BOOST_STORAGE_KEY,
  LEGACY_AVATAR_DATABASE_NAME,
  LEGACY_GAME_STORAGE_KEY,
  LEGACY_JOURNAL_DRAFTS_CLEARED_STORAGE_KEY,
  LEGACY_JOURNAL_DRAFT_STORAGE_PREFIX,
  LEGACY_QUEST_JOURNEY_STORAGE_KEY,
  LEGACY_RHYTHM_STORAGE_KEY,
  LEGACY_SEVEN_DAYS_STORAGE_KEY,
  LEGACY_SEVEN_DAYS_TUTORIAL_STORAGE_KEY,
  WEB_V2_ARCADE_BOOST_STORAGE_KEY,
  WEB_V2_AVATAR_DATABASE_NAME,
  WEB_V2_GAME_STORAGE_KEY,
  WEB_V2_JOURNAL_DRAFTS_CLEARED_STORAGE_KEY,
  WEB_V2_JOURNAL_DRAFT_STORAGE_PREFIX,
  WEB_V2_QUEST_JOURNEY_STORAGE_KEY,
  WEB_V2_RHYTHM_STORAGE_KEY,
  WEB_V2_SEVEN_DAYS_STORAGE_KEY,
  WEB_V2_SEVEN_DAYS_TUTORIAL_STORAGE_KEY,
  readWebPrivateNamespaceState,
  selectedWebPrivateAvatarDatabase,
  selectedWebPrivateStorageKey,
} from "./web-private-namespace";

/** Gives local data modules neutral names while preserving the reviewed boundary. */
export const DEVICE_JOURNEY_STORAGE_KEY = LEGACY_QUEST_JOURNEY_STORAGE_KEY;
export const PROTECTED_JOURNEY_STORAGE_KEY = WEB_V2_QUEST_JOURNEY_STORAGE_KEY;
export const DEVICE_JOURNAL_DRAFT_PREFIX = LEGACY_JOURNAL_DRAFT_STORAGE_PREFIX;
export const PROTECTED_JOURNAL_DRAFT_PREFIX =
  WEB_V2_JOURNAL_DRAFT_STORAGE_PREFIX;
export const DEVICE_JOURNAL_DRAFTS_CLEARED_KEY =
  LEGACY_JOURNAL_DRAFTS_CLEARED_STORAGE_KEY;
export const PROTECTED_JOURNAL_DRAFTS_CLEARED_KEY =
  WEB_V2_JOURNAL_DRAFTS_CLEARED_STORAGE_KEY;
export const DEVICE_RHYTHM_STORAGE_KEY = LEGACY_RHYTHM_STORAGE_KEY;
export const PROTECTED_RHYTHM_STORAGE_KEY = WEB_V2_RHYTHM_STORAGE_KEY;
export const DEVICE_GAME_STORAGE_KEY = LEGACY_GAME_STORAGE_KEY;
export const PROTECTED_GAME_STORAGE_KEY = WEB_V2_GAME_STORAGE_KEY;
export const DEVICE_SEVEN_DAYS_STORAGE_KEY = LEGACY_SEVEN_DAYS_STORAGE_KEY;
export const PROTECTED_SEVEN_DAYS_STORAGE_KEY = WEB_V2_SEVEN_DAYS_STORAGE_KEY;
export const DEVICE_SEVEN_DAYS_TUTORIAL_STORAGE_KEY =
  LEGACY_SEVEN_DAYS_TUTORIAL_STORAGE_KEY;
export const PROTECTED_SEVEN_DAYS_TUTORIAL_STORAGE_KEY =
  WEB_V2_SEVEN_DAYS_TUTORIAL_STORAGE_KEY;
export const DEVICE_ARCADE_BOOST_STORAGE_KEY =
  LEGACY_ARCADE_BOOST_STORAGE_KEY;
export const PROTECTED_ARCADE_BOOST_STORAGE_KEY =
  WEB_V2_ARCADE_BOOST_STORAGE_KEY;
export const DEVICE_AVATAR_DATABASE_NAME = LEGACY_AVATAR_DATABASE_NAME;
export const PROTECTED_AVATAR_DATABASE_NAME = WEB_V2_AVATAR_DATABASE_NAME;

/** Selects the exact reviewed storage key for the current local-data owner. */
export const selectDevicePrivateStorageKey = selectedWebPrivateStorageKey;

/** Selects the exact reviewed avatar database for the current local-data owner. */
export const selectDevicePrivateAvatarDatabase =
  selectedWebPrivateAvatarDatabase;

/** Reports the reviewed local-data namespace without exposing its implementation. */
export const readDevicePrivateStorageState = readWebPrivateNamespaceState;
