/**
 * Build typed seed data files from the verified content result.
 *
 *   scratchpad/seed-result.json  ──►  src/data/seed/{quests,prayer-prompts,reflection-prompts,milestones}.ts
 *
 * Short scripture passages (<= 4 verses) are hydrated with exact World English
 * Bible (public domain) text pulled from the imported Bible data, so quest
 * cards can show real verse text with no licensing concern.
 *
 * Run: node scripts/build-seed.mjs <path-to-seed-result.json>
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";

const SRC = process.argv[2];
if (!SRC || !existsSync(SRC)) {
  console.error("Usage: node scripts/build-seed.mjs <seed-result.json>");
  process.exit(1);
}
const result = JSON.parse(readFileSync(SRC, "utf8"));
const BIBLE_DIR = path.join(process.cwd(), "src/data/bible");
const booksMeta = JSON.parse(
  readFileSync(path.join(BIBLE_DIR, "books.json"), "utf8")
);

// Reference book name -> slug (covers singular/variant forms in references)
const nameToSlug = new Map();
for (const b of booksMeta) {
  nameToSlug.set(b.name.toLowerCase(), b.slug);
}
const ALIASES = {
  psalm: "psalms",
  "song of songs": "song-of-solomon",
  canticles: "song-of-solomon",
};
for (const [alias, slug] of Object.entries(ALIASES)) nameToSlug.set(alias, slug);

const bookCache = new Map();
function loadBook(slug) {
  if (!bookCache.has(slug)) {
    bookCache.set(
      slug,
      JSON.parse(readFileSync(path.join(BIBLE_DIR, `${slug}.json`), "utf8"))
    );
  }
  return bookCache.get(slug);
}

/** Parse "1 Thessalonians 5:11" or "Psalm 23:1-6" -> {slug, chapter, start, end}. */
function parseRef(ref) {
  const m = ref.match(/^(.+?)\s+(\d+):(\d+)(?:-(\d+))?$/);
  if (!m) return null;
  const [, bookName, chap, start, end] = m;
  const slug = nameToSlug.get(bookName.trim().toLowerCase());
  if (!slug) return null;
  return {
    slug,
    chapter: Number(chap),
    start: Number(start),
    end: end ? Number(end) : Number(start),
  };
}

/** Return exact verse text for short passages, else null. */
function hydrate(ref) {
  const parsed = parseRef(ref);
  if (!parsed) {
    console.warn(`  ! unresolved reference: "${ref}"`);
    return null;
  }
  if (parsed.end - parsed.start > 3) return null; // keep card text short
  const book = loadBook(parsed.slug);
  const ch = book.chapters[parsed.chapter - 1];
  if (!ch) {
    console.warn(`  ! missing ${ref}`);
    return null;
  }
  const text = ch.slice(parsed.start - 1, parsed.end).join(" ").trim();
  if (!text) return null;
  // Reject snapshots that still carry paired double-quote or nested
  // single-quote speech artifacts after trimming a wrapping quote — those read
  // as malformed inside our own quote marks, so the card shows the reference
  // only. (’ apostrophes in contractions are fine.)
  const trimmed = text
    .replace(/^[“”‘’"']+\s*/, "")
    .replace(/\s*[“”‘’"']+$/, "")
    .trim();
  if (/[“”"‘]/.test(trimmed)) return null;
  return text;
}

const banner = (title) =>
  `// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.\n` +
  `// ${title}\n` +
  `// Content verified by the biblequest-seed-content workflow (safety + tone + theology lenses).\n` +
  `// Scripture text: World English Bible (public domain).\n\n`;

// --------------------------------------------------------------------------
// Quests
// --------------------------------------------------------------------------
let hydrated = 0;
const quests = result.quests.map((q) => {
  const scriptureText = hydrate(q.scripture_reference);
  if (scriptureText) hydrated++;
  return {
    slug: q.slug,
    title: q.title,
    category: q.category,
    durationMinutes: q.duration_minutes,
    difficulty: q.difficulty,
    energyLevel: q.energy_level,
    soloOrSocial: q.solo_or_social,
    indoorOrOutdoor: q.indoor_or_outdoor,
    invitation: q.invitation,
    whyItMatters: q.why_it_matters,
    scriptureReference: q.scripture_reference,
    ...(scriptureText ? { scriptureText } : {}),
    reflectionPrompt: q.reflection_prompt,
    prayerPrompt: q.prayer_prompt,
    growthType: q.growth_type,
    tags: q.tags,
    seasonTags: q.season_tags,
    traditionTags: q.tradition_tags,
    sensitivityTags: q.sensitivity_tags,
    isPremium: q.is_premium,
  };
});

writeFileSync(
  path.join(process.cwd(), "src/data/seed/quests.ts"),
  banner("Quest templates") +
    `import type { QuestTemplate } from "@/lib/questos/types";\n\n` +
    `export const seedQuests: QuestTemplate[] = ${JSON.stringify(quests, null, 2)};\n\n` +
    `export const questBySlug = new Map(seedQuests.map((q) => [q.slug, q]));\n`
);

// --------------------------------------------------------------------------
// Prayer prompts
// --------------------------------------------------------------------------
const prayerPrompts = result.prayerPrompts.map((p) => ({
  id: p.id,
  text: p.text,
  category: p.category,
}));
writeFileSync(
  path.join(process.cwd(), "src/data/seed/prayer-prompts.ts"),
  banner("Prayer prompts") +
    `import type { PrayerPromptSeed } from "@/lib/questos/types";\n\n` +
    `export const prayerPrompts: PrayerPromptSeed[] = ${JSON.stringify(prayerPrompts, null, 2)};\n`
);

// --------------------------------------------------------------------------
// Reflection prompts
// --------------------------------------------------------------------------
const reflectionPrompts = result.reflectionPrompts.map((p) => ({
  id: p.id,
  text: p.text,
  context: p.context,
}));
writeFileSync(
  path.join(process.cwd(), "src/data/seed/reflection-prompts.ts"),
  banner("Reflection prompts") +
    `import type { ReflectionPromptSeed } from "@/lib/questos/types";\n\n` +
    `export const reflectionPrompts: ReflectionPromptSeed[] = ${JSON.stringify(reflectionPrompts, null, 2)};\n`
);

// --------------------------------------------------------------------------
// Milestones
// --------------------------------------------------------------------------
const milestones = result.milestones.map((m) => ({
  key: m.key,
  title: m.title,
  description: m.description,
  milestoneType: m.milestone_type,
  requirementMetric: m.requirement_metric,
  requirementCount: m.requirement_count,
  iconKey: m.icon_key,
}));
writeFileSync(
  path.join(process.cwd(), "src/data/seed/milestones.ts"),
  banner("Milestones") +
    `import type { MilestoneSeed } from "@/lib/questos/types";\n\n` +
    `export const seedMilestones: MilestoneSeed[] = ${JSON.stringify(milestones, null, 2)};\n`
);

console.log(
  `Seed written: ${quests.length} quests (${hydrated} with verse text), ` +
    `${prayerPrompts.length} prayer prompts, ${reflectionPrompts.length} reflection prompts, ` +
    `${milestones.length} milestones.`
);
